-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('DBO.ACM_SETTING_MOTIFS_REJET', 'U') IS NOT NULL
DROP TABLE DBO.ACM_SETTING_MOTIFS_REJET;
-------------

----- TABLE : ACM_SETTING_MOTIFS_REJET
CREATE TABLE ACM_SETTING_MOTIFS_REJET(
    ID_ACM_SETTING_MOTIFS_REJET BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CATEGORIE VARCHAR (100) NOT NULL, -- REJET / CORRECTIFS
	CODE  VARCHAR (256) NOT NULL,
	LIBELLE  VARCHAR (512) NULL,
    DESCRIPTION  VARCHAR (512) NULL,
	ID_PRODUIT INT NULL,
	 
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
