-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_USERS', 'U') IS NOT NULL
DROP TABLE dbo.ACM_USERS;

IF OBJECT_ID('dbo.ACM_ENVIRONNEMENT', 'U') IS NOT NULL
DROP TABLE dbo.ACM_ENVIRONNEMENT;

IF OBJECT_ID('dbo.ACM_REPORT_VISIT', 'U') IS NOT NULL
DROP TABLE dbo.ACM_REPORT_VISIT;

IF OBJECT_ID('dbo.ACM_LOAN', 'U') IS NOT NULL
DROP TABLE dbo.ACM_LOAN;
-------------

----- TABLE : LOAN 
CREATE TABLE ACM_LOAN(

	ID_ACM_LOAN BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,   

	ID_LOAN_EXTERN BIGINT NOT NULL,

	ID_ACCOUNT_EXTERN BIGINT,

	ACCOUNT_NUMBER_EXTERN VARCHAR (256),

	STATUT INT NOT NULL,

	PROCESS_INSTANCE_ID VARCHAR (256) NULL,

	PORTFOLIO_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE PROFIL COTÉ ABACUS

	ACM_ENABLED BIT NOT NULL DEFAULT 1,

	DATE_INSERTION DATE NULL,
	
	INSERT_BY  VARCHAR (256) NULL,

	DATE_LAST_UPDATE DATE NULL,

	UPDATED_BY  VARCHAR (256) NULL,

	ACM_VERSION INT NULL);
-------------------

----- TABLE : USERS 
CREATE TABLE ACM_USERS(   

	USERNAME VARCHAR (256) NOT NULL PRIMARY KEY,   

	PASSWORD VARCHAR (256) NOT NULL,

	ACCOUNT_PORTFOLIO_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE PORTFOLIO COTÉ ABACUS

	USER_EXTERN_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE USER COTÉ ABACUS

	USER_PROFIL_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE PROFIL COTÉ ABACUS

	ID_USER BIGINT NOT NULL IDENTITY(1,1), 

	RESPONSABLE_ID BIGINT NOT NULL , --- 0 : PAS DE RESPONSABLE ACM_ENABLED BIT NOT NULL,

	ACM_ENABLED BIT NOT NULL DEFAULT 1,

	DATE_INSERTION DATE NULL,
	
	INSERT_BY  VARCHAR (256) NULL,

	DATE_LAST_UPDATE DATE NULL,

	UPDATED_BY  VARCHAR (256) NULL,

	ACM_VERSION INT NULL)
-------------------

----- TABLE : ACM_ENVIRONNEMENT 
CREATE TABLE ACM_ENVIRONNEMENT(   

	ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,   

	ACM_ENVIRONNEMENT_KEY VARCHAR (256) NOT NULL,

	ACM_ENVIRONNEMENT_VALUE VARCHAR (256) NOT NULL,

	ACM_ENABLED BIT NOT NULL DEFAULT 1,

	DATE_INSERTION DATE NULL,
	
	INSERT_BY  VARCHAR (256) NULL,

	DATE_LAST_UPDATE DATE NULL,

	UPDATED_BY  VARCHAR (256) NULL,

	ACM_VERSION INT NULL)
------------------- 


----- TABLE : ACM_REPORT_VISIT 
CREATE TABLE ACM_REPORT_VISIT(
	
	ID_ACM_REPORT_VISIT BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,  
	
	ID_ACM_LOAN BIGINT NOT NULL,

	DESCRIPTION VARCHAR(5000) NOT NULL,
	
	TITLE VARCHAR(255) NOT NULL,

	VISIT_BY VARCHAR (256) NULL,
	
	ACM_ENABLED BIT NOT NULL DEFAULT 1,

	DATE_INSERTION DATE NULL,
	
	INSERT_BY  VARCHAR (256) NULL,

	DATE_LAST_UPDATE DATE NULL,

	UPDATED_BY  VARCHAR (256) NULL,

	ACM_VERSION INT NULL,

	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);


