-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_DOC_LOAN', 'U') IS NOT NULL
DROP TABLE dbo.ACM_DOC_LOAN;
-------------

----- TABLE : ACM_DOC_LOAN
 
CREATE TABLE ACM_DOC_LOAN(
    ID_ACM_DOC_LOAN BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT NOT NULL,
	ID_DOCUMENT_GED VARCHAR (256) NULL,
    TITRE  VARCHAR (512) NOT NULL,
    DESCRIPTION  VARCHAR (1000) NULL,
    AUTEUR VARCHAR (256) NULL,
    DATE_CREATION DATE NULL,
    TYPE_MIME VARCHAR (50) NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	
	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);