-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('DBO.ACM_SETTING_DOCS', 'U') IS NOT NULL
DROP TABLE DBO.ACM_SETTING_DOCS;
-------------

----- TABLE : ACM_SETTING_DOCS
CREATE TABLE ACM_SETTING_DOCS(
    ID_ACM_SETTING_DOCS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CATEGORIE VARCHAR (100) NOT NULL, -- PRODUIT / CLIENT / AUTRE
	ID_PRODUIT INT NULL,
	CODE  VARCHAR (256) NOT NULL,
	LIBELLE  VARCHAR (512) NULL,
    DESCRIPTION  VARCHAR (512) NULL,
	MANDATORY BIT NULL,
	DATE_DEBUT DATE NULL,
	DATE_FIN DATE NULL,
	 
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);