update acm_habilitation set ACM_WEB_ROUTE = 'screening'  where GROUPE_ID = '20' and  VALUE = 'REJECT_ISCORE_GUARANTOR'
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],description,CATEGORY) 
VALUES ('RENEWEL_LOAN_CONDITION', '0', 1, GETDATE(), 0,'Renewel loan condition', 'FUNCTIONAL');