--- TABLE : ACM_UDF_LIST_VALUES
ALTER TABLE ACM_UDF_LIST_VALUES ADD PARENT_UDF_LIST_VALUE BIGINT DEFAULT 0;
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE = 0

--- TABLE : ACM_UDF_FIELD
UPDATE ACM_UDF_FIELD SET ACM_PARENT_UDF_FIELD_Value = 0

UPDATE ACM_UDF_FIELD 
SET ID_ACM_PARENT_UDF_FIELD = (SELECT ID_ABACUS_UDF_FIELD from ACM_UDF_FIELD WHERE FIELD_NAME = 'Industry Code Level 1')
WHERE FIELD_NAME = 'Industry Code Level 2'


UPDATE ACM_UDF_FIELD 
SET ID_ACM_PARENT_UDF_FIELD = (SELECT ID_ABACUS_UDF_FIELD from ACM_UDF_FIELD WHERE FIELD_NAME = 'Industry Code Level 2')
WHERE FIELD_NAME = 'Industry Code Level 3'