  -------------------
----- TABLE : ACM_SETTING_CHARGE_FEE 
CREATE TABLE ACM_SETTING_CHARGE_FEE(   
	ID_ACM_SETTING_CHARGE_FEE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ABACUS smallint NOT NULL,
	LABEL VARCHAR (256) NULL,
	CODE VARCHAR (256)  NULL,
	VALUE VARCHAR (256) NULL,
	AMOUNT decimal(16, 4) NULL,
	PERCENTAGE  INT NULL,
	ID_LOAN_EXTERN BIGINT NULL,
	ACM_ID_COLLECTION BIGINT NULL,
			
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);


CREATE TABLE ACM_WORKFLOW_STEP_SETTING_CHARGE_FEES (
    ID_ACM_WORKFLOW_STEP BIGINT,
    ID_ACM_SETTING_CHARGE_FEE BIGINT,
    PRIMARY KEY (ID_ACM_WORKFLOW_STEP, ID_ACM_SETTING_CHARGE_FEE),
    FOREIGN KEY (ID_ACM_WORKFLOW_STEP) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP), 
    FOREIGN KEY (ID_ACM_SETTING_CHARGE_FEE) REFERENCES ACM_SETTING_CHARGE_FEE(ID_ACM_SETTING_CHARGE_FEE) 
);


CREATE TABLE ACM_COLLECTION_STEP_SETTING_CHARGE_FEES (
    ID_ACM_COLLECTION_STEP BIGINT,
    ID_ACM_SETTING_CHARGE_FEE BIGINT,
    PRIMARY KEY (ID_ACM_COLLECTION_STEP, ID_ACM_SETTING_CHARGE_FEE),
    FOREIGN KEY (ID_ACM_COLLECTION_STEP) REFERENCES ACM_COLLECTION_STEP(ID_ACM_COLLECTION_STEP), 
    FOREIGN KEY (ID_ACM_SETTING_CHARGE_FEE) REFERENCES ACM_SETTING_CHARGE_FEE(ID_ACM_SETTING_CHARGE_FEE) 
);

----- TABLE : ACM_CHARGE_FEE 
CREATE TABLE ACM_CHARGE_FEES(   
	ID_ACM_CHARGE_FEE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ABACUS smallint NOT NULL,
	ID_ACM_SETTING_CHARGE_FEE BIGINT NOT NULL,
	ID_ACM_LOAN_INSTANCE BIGINT NULL,
	ID_ACM_COLLECTION_INSTANCE BIGINT NULL,
	AMOUNT decimal(16, 4) NULL,
	CHARGED BIT NULL,
	LABEL VARCHAR (256) NULL,
	CODE VARCHAR (256)  NULL,
	VALUE VARCHAR (256) NULL,

	FOREIGN KEY (ID_ACM_LOAN_INSTANCE) REFERENCES ACM_LOAN_INSTANCE (ID_ACM_LOAN_INSTANCE),
	FOREIGN KEY (ID_ACM_COLLECTION_INSTANCE) REFERENCES ACM_COLLECTION_INSTANCE (ID_ACM_COLLECTION_INSTANCE),

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
