INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
  select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CUSTOMER_DECISION' ,'customer-decision' ,'CHANGE_DATA'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
  select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_UPLOAD_SIGNED_AGREEMENT' ,'upload-signed-agreement' ,'CHANGE_DATA'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE
  