CREATE TABLE ACM_HISTORY(
    ID_ACM_HISTORY BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,  
    ID_OBJECT  BIGINT, 
    ACTIONS VARCHAR (256) NULL,
    ACTION_BY VARCHAR (256) NULL,     
    DATE_ACTION  VARCHAR (256) NULL,
    VALUE_OBJECT VARCHAR (3000) NULL,
    TYPE_OBJECT  VARCHAR (256) NULL
);


