INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('ACM','REVIEW','IHM_LOAN_REVIEW','REVIEW',34,1,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,1 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,2 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,4 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,5 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,6 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,7 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,8 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,9 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,10 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,11 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,12 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,13 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,0,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('READ','ACM' ,14 ,'IHM_LOAN_REVIEW' ,'loan-review' ,'REVIEW' ,1,GETDATE(),'ADMIN',0);