-------------
-------------
----ACM-917
-------------
-------------
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('SUBSCRIBER_SERIAL_NUMBER', '1234567890', 1, '2020-12-28', 0)