-- table damaged data added from abacus

CREATE TABLE ACM_DAMAGED_DATA(

    ID_ACM_DAMAGED_DATA BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CUSTOMER_EXTERNE BIGINT,
	ID_ACCOUNT_EXTERN BIGINT,
	DAMAGED_OBJECT_DATA VARCHAR (256) NOT NULL,
	EXCEPTION_DETAILS  NVARCHAR (MAX) NULL,
    ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,

);
 -- LIMITE_ID_CUSTOMER_EXTERNE
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('LIMITE_ID_CUSTOMER_EXTERNE', '1', 1, GETDATE(), 0)