
----- TABLE ASSOCIATION : ACM_WORKFLOW_STEP_ACM_GROUPE_PARTICIPANT
   CREATE TABLE ACM_WORKFLOW_STEP_ACM_GROUPE_PARTICIPANT (
    ACM_LOAN_STEP_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
    PRIMARY KEY (ACM_LOAN_STEP_ID,ACM_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE),
); 


----- TABLE ASSOCIATION : ACM_WORKFLOW_STEP_ACM_GROUPE_APPROVAL
   CREATE TABLE ACM_WORKFLOW_STEP_ACM_GROUPE_APPROVAL (
    ACM_LOAN_STEP_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
    PRIMARY KEY (ACM_LOAN_STEP_ID,ACM_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE)
); 



----- TABLE ASSOCIATION : ACM_LOAN_INSTANCE_ACM_GROUPE_APPROVAL
   CREATE TABLE ACM_LOAN_INSTANCE_ACM_GROUPE_APPROVAL (
    LOAN_INSTANCE_GROUPE_ID  BIGINT NOT NULL IDENTITY(1,1),
    ACM_LOAN_INSTANCE_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
	ACM_OWNER VARCHAR (512) NULL,
	ACM_OWNER_NAME VARCHAR (1000) NULL,
	ACM_GROUPE_NAME VARCHAR (256) NULL,
	ACM_GROUPE_CODE VARCHAR (256) NULL,
	ACM_LOAN_VALIDATION BIT NULL,

    ACM_ENABLED BIT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,

    PRIMARY KEY (ACM_LOAN_INSTANCE_ID,ACM_GROUPE_ID,LOAN_INSTANCE_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_INSTANCE_ID) REFERENCES ACM_LOAN_INSTANCE (ID_ACM_LOAN_INSTANCE),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE),
); 


