ALTER TABLE ACM_USERS ADD FAILED_ATTEMPTS smallint not null DEFAULT (0), PWD_EXPIRY_DATE date ;

INSERT INTO ACM_ENVIRONNEMENT(ACM_ENVIRONNEMENT_KEY, ACM_ENVIRONNEMENT_VALUE, ACM_ENABLED, DATE_INSERTION, ACM_VERSION, CATEGORY) 
VALUES ('USER_PWD_EXPIRE_DELAY', '90', 1, getdate(), 0, 'TECHNICAL');

INSERT INTO ACM_ENVIRONNEMENT(ACM_ENVIRONNEMENT_KEY, ACM_ENVIRONNEMENT_VALUE, ACM_ENABLED, DATE_INSERTION, ACM_VERSION, CATEGORY) 
VALUES ('USER_PWD_FAILED_ATTEMPTS_LIMIT', '5', 1, getdate(), 0, 'TECHNICAL');