
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_TOPUP_REFINANCE_LOAN' ,'topup-refinance-loan' ,'IHM'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE

ALTER TABLE oauth_access_token
ALTER COLUMN user_name varchar(2000);

ALTER DATABASE abacus_tamkeen  
SET COMPATIBILITY_LEVEL = 130;  
GO