
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [racine_id])		    
		VALUES('ACM','IHM_LEGAL','legal' ,'page LEGAL' ,1,GETDATE(),'ADMIN',0,4);
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [racine_id])		    
		VALUES('ACM','IHM_UNASSIGNED_LEGAL','unassigned-legal' ,'page UNASSIGNED LEGAL' ,1,GETDATE(),'ADMIN',0,4);


 -- ACM_HABILITATION
-----------------------------
-- 
----------------------------
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LEGAL' ,'legal' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'LEGAL SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_UNASSIGNED_LEGAL' ,'unassigned-legal' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'UNASSIGNED LEGAL SCREEN' from ACM_GROUPE


UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE
where CODE_IHM_ROUTE = 'IHM_LEGAL'

UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE
where CODE_IHM_ROUTE = 'IHM_UNASSIGNED_LEGAL'