INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('MAX_SIZE_FILE_UPLOAD', '5242880', 1, '2020-06-17', 0);

INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('ALLOWED_TYPE_FILE_UPLOAD', 'application/pdf,application/msword,image/jpeg,image/png', 1, '2020-06-17', 0);