 -----------------------
-----------------------
-- DATA [ACM_SETTING_LEVEL_PROCESS]
-----------------------
 
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (1,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (1,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (1,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (1,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (2,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (2,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (2,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (2,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (3,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (3,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (3,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (3,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

 INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (5,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (5,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (5,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (5,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (6,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (6,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (6,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (6,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (20,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (20,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (20,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (20,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (21,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (21,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (21,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (21,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (22,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (22,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (22,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (22,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (23,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (23,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (23,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (23,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (26,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (26,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (26,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (26,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);
 
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (27,10000,'L1 allowed to approve Loan with amount <=10000',1,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (27,20000,'L2 allowed to approve Loan with amount <=20000',2,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (27,30000,'L3 allowed to approve Loan with amount <=30000',3,
	 1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL_PROCESS]([ID_PRODUCT],[AMOUNT],[DESCRIPTION],[ID_ACM_SETTING_LEVEL],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (27,40000,'L4 allowed to approve Loan with amount <=40000',4,
	 1,GETDATE(),'ADMIN',0);