-- DATE_LAST_UPDATE_REFRESH_LIMIT_EXPENSES
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('DATE_LAST_UPDATE_REFRESH_LIMIT_EXPENSES', '', 1, GETDATE(), 0, 'FUNCTIONAL');