IF OBJECT_ID('dbo.ACM_TRANSVERS_HISTORY', 'U') IS NOT NULL
DROP TABLE dbo.ACM_TRANSVERS_HISTORY;

CREATE TABLE ACM_TRANSVERS_HISTORY(

ID_ACM_TRANSVERS_HISTORY BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
OBJECT_VALUE VARCHAR (256) NULL,
METHODE VARCHAR (256) NULL,
URI VARCHAR (256) NULL,
REPONSE_STATUS VARCHAR (50) NULL,
REQUEST_VALUE VARCHAR(MAX) NULL,
RESPONSE_VALUE VARCHAR(MAX) NULL,

ACM_ENABLED BIT NOT NULL,
DATE_INSERTION DATETIME NULL,
INSERT_BY  VARCHAR (256) NULL,
DATE_LAST_UPDATE DATETIME NULL,
UPDATED_BY  VARCHAR (256) NULL,
ACM_VERSION INT NULL
)

