UPDATE ACM_UDF_FIELD SET ACM_PARENT_UDF_FIELD_Value = 0
UPDATE ACM_UDF_FIELD SET ID_ACM_PARENT_UDF_FIELD = (SELECT ID_ABACUS_UDF_FIELD from ACM_UDF_FIELD WHERE FIELD_NAME = 'Industry Code Level 1') WHERE FIELD_NAME = 'Industry Code Level 2'
UPDATE ACM_UDF_FIELD SET ID_ACM_PARENT_UDF_FIELD = (SELECT ID_ABACUS_UDF_FIELD from ACM_UDF_FIELD WHERE FIELD_NAME = 'Industry Code Level 2') WHERE FIELD_NAME = 'Industry Code Level 3'
UPDATE ACM_UDF_FIELD SET FIELD_MASC = '^(1)+\d{9}$' WHERE ID_ABACUS_UDF_FIELD = 3
UPDATE ACM_UDF_FIELD SET FIELD_MASC = '^(2)+\d{9}$' WHERE ID_ABACUS_UDF_FIELD = 4

UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE = 0

UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=609 WHERE ID_UDF_LIST_VALUE=614
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=609 WHERE ID_UDF_LIST_VALUE=615
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=609 WHERE ID_UDF_LIST_VALUE=616
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=609 WHERE ID_UDF_LIST_VALUE=617
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=618
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=619
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=620
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=621
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=622
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=623
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=624
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=625
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=626
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=627
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=628
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=637
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=630
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=631
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=610 WHERE ID_UDF_LIST_VALUE=632
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=633
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=634
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=635
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=636
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=629
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=638
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=639
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=612 WHERE ID_UDF_LIST_VALUE=886
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=640
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=641
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=642
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=643
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=644
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=887
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=646
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=645
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=647
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=648
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=649
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=650
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=613 WHERE ID_UDF_LIST_VALUE=651

UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=614 WHERE ID_UDF_LIST_VALUE=652
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=614 WHERE ID_UDF_LIST_VALUE=653
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=614 WHERE ID_UDF_LIST_VALUE=654
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=614 WHERE ID_UDF_LIST_VALUE=655
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=615 WHERE ID_UDF_LIST_VALUE=656
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=615 WHERE ID_UDF_LIST_VALUE=657
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=616 WHERE ID_UDF_LIST_VALUE=658
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=616 WHERE ID_UDF_LIST_VALUE=658
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=617 WHERE ID_UDF_LIST_VALUE=659
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=617 WHERE ID_UDF_LIST_VALUE=660
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=617 WHERE ID_UDF_LIST_VALUE=661
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=618 WHERE ID_UDF_LIST_VALUE=662
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=618 WHERE ID_UDF_LIST_VALUE=663
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=664
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=665
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=666
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=667
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=668
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=669
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=670
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=671
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=672
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=673
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=619 WHERE ID_UDF_LIST_VALUE=674
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=675
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=676
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=677
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=678
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=621 WHERE ID_UDF_LIST_VALUE=679
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=621 WHERE ID_UDF_LIST_VALUE=680
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=621 WHERE ID_UDF_LIST_VALUE=681
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=682
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=683
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=684
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=685
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=686
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=687
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=688
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=689
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=690
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=622 WHERE ID_UDF_LIST_VALUE=691
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=623 WHERE ID_UDF_LIST_VALUE=692
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=623 WHERE ID_UDF_LIST_VALUE=693
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=623 WHERE ID_UDF_LIST_VALUE=694
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=623 WHERE ID_UDF_LIST_VALUE=695
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=623 WHERE ID_UDF_LIST_VALUE=696
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=697
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=698
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=699
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=700
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=701
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=702
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=703
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=704
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=705
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=706
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=707
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=708
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=624 WHERE ID_UDF_LIST_VALUE=709
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=625 WHERE ID_UDF_LIST_VALUE=710
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=625 WHERE ID_UDF_LIST_VALUE=711
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=625 WHERE ID_UDF_LIST_VALUE=712
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=625 WHERE ID_UDF_LIST_VALUE=713
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=625 WHERE ID_UDF_LIST_VALUE=714
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=626 WHERE ID_UDF_LIST_VALUE=715
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=626 WHERE ID_UDF_LIST_VALUE=716
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=626 WHERE ID_UDF_LIST_VALUE=717
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=718
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=719
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=720
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=721
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=722
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=723
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=724
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=725
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=726
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=727
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=728
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=729
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=730
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=731
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=732
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=627 WHERE ID_UDF_LIST_VALUE=733
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=734
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=735
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=736
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=737
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=738
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=739
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=740
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=741
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=742
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=743
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=744
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=628 WHERE ID_UDF_LIST_VALUE=745
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=637 WHERE ID_UDF_LIST_VALUE=746
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=637 WHERE ID_UDF_LIST_VALUE=747
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=637 WHERE ID_UDF_LIST_VALUE=748
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=749
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=750
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=751
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=752
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=753
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=754
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=630 WHERE ID_UDF_LIST_VALUE=755
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=756
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=757
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=758
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=759
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=760
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=761
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=631 WHERE ID_UDF_LIST_VALUE=762
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=632 WHERE ID_UDF_LIST_VALUE=763
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=764
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=765
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=766
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=767
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=768
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=769
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=770
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=633 WHERE ID_UDF_LIST_VALUE=771
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=772
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=773
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=774
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=775
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=620 WHERE ID_UDF_LIST_VALUE=776
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=634 WHERE ID_UDF_LIST_VALUE=777
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=634 WHERE ID_UDF_LIST_VALUE=778
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=634 WHERE ID_UDF_LIST_VALUE=779
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=634 WHERE ID_UDF_LIST_VALUE=780
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=635 WHERE ID_UDF_LIST_VALUE=781
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=635 WHERE ID_UDF_LIST_VALUE=782
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=635 WHERE ID_UDF_LIST_VALUE=783
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=784
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=785
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=786
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=787
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=788
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=789
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=790
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=791
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=636 WHERE ID_UDF_LIST_VALUE=792
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=629 WHERE ID_UDF_LIST_VALUE=793
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=629 WHERE ID_UDF_LIST_VALUE=794
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=629 WHERE ID_UDF_LIST_VALUE=795
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=629 WHERE ID_UDF_LIST_VALUE=796
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=629 WHERE ID_UDF_LIST_VALUE=797
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=638 WHERE ID_UDF_LIST_VALUE=798
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=639 WHERE ID_UDF_LIST_VALUE=799
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=800
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=801
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=802
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=803
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=804
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=805
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=806
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=807
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=808
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=809
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=640 WHERE ID_UDF_LIST_VALUE=810
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=811
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=812
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=813
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=814
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=815
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=816
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=817
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=818
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=819
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=820
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=821
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=642 WHERE ID_UDF_LIST_VALUE=822
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=642 WHERE ID_UDF_LIST_VALUE=823
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=642 WHERE ID_UDF_LIST_VALUE=824
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=642 WHERE ID_UDF_LIST_VALUE=825
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=826
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=827
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=828
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=829
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=830
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=643 WHERE ID_UDF_LIST_VALUE=831
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=644 WHERE ID_UDF_LIST_VALUE=832
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=644 WHERE ID_UDF_LIST_VALUE=833
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=644 WHERE ID_UDF_LIST_VALUE=834
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=644 WHERE ID_UDF_LIST_VALUE=835
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=836
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=837
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=838
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=839
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=840
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=841
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=842
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=843
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=844
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=845
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=846
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=847
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=848
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=849
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=887 WHERE ID_UDF_LIST_VALUE=850
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=851
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=852
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=853
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=854
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=855
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=646 WHERE ID_UDF_LIST_VALUE=856
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=857
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=858
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=859
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=860
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=861
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=862
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=863
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=864
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=865
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=866
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=867
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=647 WHERE ID_UDF_LIST_VALUE=868
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=869
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=870
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=871
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=872
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=873
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=874
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=648 WHERE ID_UDF_LIST_VALUE=875
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=649 WHERE ID_UDF_LIST_VALUE=876
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=649 WHERE ID_UDF_LIST_VALUE=877
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=649 WHERE ID_UDF_LIST_VALUE=878
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=650 WHERE ID_UDF_LIST_VALUE=879
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=651 WHERE ID_UDF_LIST_VALUE=880
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=651 WHERE ID_UDF_LIST_VALUE=881
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=651 WHERE ID_UDF_LIST_VALUE=882
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=621 WHERE ID_UDF_LIST_VALUE=888
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=626 WHERE ID_UDF_LIST_VALUE=889
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=638 WHERE ID_UDF_LIST_VALUE=890
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=891
UPDATE ACM_UDF_LIST_VALUES SET PARENT_UDF_LIST_VALUE=641 WHERE ID_UDF_LIST_VALUE=892

update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(select ID_ACM_UDF_LIST_VALUES from ACM_UDF_LIST_VALUES where NAME= 'BMISEGCXXXX') where NAME like 'BMISEGCXXXX%' and name !='BMISEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'NBEGEGCXXXX') where name like 'NBEGEGCXXXX%' and name !='NBEGEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'BCAIEGCXXXX') where name like 'BCAIEGCXXXX%' and name !='BCAIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ALEXEGCXXXX') where name like 'ALEXEGCXXXX%' and name !='ALEXEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'HDBKEGCAXXX') where name like 'HDBKEGCAXXX%' and name !='HDBKEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'CIBEEGCXXXX') where name like 'CIBEEGCXXXX%' and name !='CIBEEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'EBBKEGCXXXX') where name like 'EBBKEGCXXXX%' and name !='EBBKEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'EAABEGCXXXX') where name like 'EAABEGCXXXX%' and name !='EAABEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ECBAEGCAXXX') where name like 'ECBAEGCAXXX%' and name !='ECBAEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ARLBEGCAXXX') where name like 'ARLBEGCAXXX%' and name !='ARLBEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ARAIEGCXXXX') where name like 'ARAIEGCXXXX%' and name !='ARAIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'NBADEGCAXXX') where name like 'NBADEGCAXXX%' and name !='NBADEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ARABEGCXXXX') where name like 'ARABEGCXXXX%' and name !='ARABEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'EXDEEGCXXXX') where name like 'EXDEEGCXXXX%' and name !='EXDEEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'FIEGEGCXXXX') where name like 'FIEGEGCXXXX%' and name !='FIEGEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'MIDBEGCXXXX') where name like 'MIDBEGCXXXX%' and name !='MIDBEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'NBOMEGCXXXX') where name like 'NBOMEGCXXXX%' and name !='NBOMEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'WABAEGCXXXX') where name like 'WABAEGCXXXX%' and name !='WABAEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'DEIBEGCXXXX') where name like 'DEIBEGCXXXX%' and name !='DEIBEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'SBNKEGCXXXX') where name like 'SBNKEGCXXXX%' and name !='SBNKEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'AGRIEGCXXXX') where name like 'AGRIEGCXXXX%' and name !='AGRIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ALECEGALXXX') where name like 'ALECEGALXXX%' and name !='ALECEGALXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'MRBAEGCXXXX') where name like 'MRBAEGCXXXX%' and name !='MRBAEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'BCBIEGCXXXX') where name like 'BCBIEGCXXXX%' and name !='BCBIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'AGRIEGCXXXX') where name like 'AGRIEGCXXXX%' and name !='AGRIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ABRKEGCAXXX') where name like 'ABRKEGCAXXX%' and name !='ABRKEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'SUCAEGCXXXX') where name like 'SUCAEGCXXXX%' and name !='SUCAEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'CITIEGCXXXX') where name like 'CITIEGCXXXX%' and name !='CITIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'AGRIEGCXXXX') where name like 'AGRIEGCXXXX%' and name !='AGRIEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'DIBBEGCAXXX') where name like 'DIBBEGCAXXX%' and name !='DIBBEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'MSHQEGCAXXX') where name like 'MSHQEGCAXXX%' and name !='MSHQEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'AUDBEGCAXXX') where name like 'AUDBEGCAXXX%' and name !='AUDBEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'UBOEEGCXXXX') where name like 'UBOEEGCXXXX%' and name !='UBOEEGCXXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'EGGBEGCAXXX') where name like 'EGGBEGCAXXX%' and name !='EGGBEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'ETHNEGCAXXX') where name like 'ETHNEGCAXXX%' and name !='ETHNEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'AINBEGCAXXX') where name like 'AINBEGCAXXX%' and name !='AINBEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'BDACEGCAXXX') where name like 'BDACEGCAXXX%' and name !='BDACEGCAXXX';
update ACM_UDF_LIST_VALUES set PARENT_UDF_LIST_VALUE=(SELECT ID_ACM_UDF_LIST_VALUES FROM ACM_UDF_LIST_VALUES where name= 'CBEGEGCXXXX') where name like 'CBEGEGCXXXX%' and name !='CBEGEGCXXXX';
