-- ACM_HABILITATION_IHM_ROUTE
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]
([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
VALUES('ACM','IHM_CUSTOMER_360','customer-360' ,'page customer 360' ,1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]
([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
VALUES('ACM','IHM_CUSTOMER_360_DETAILS','customer-360-details' ,'page customer 360 details' ,1,GETDATE(),'ADMIN',0);

----------------------------
-- ACM_HABILITATION_IHM_BUTTON
-----------------------------
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('ACM','CUSTOMER_360','IHM_CUSTOMER_360','CUSTOMER_360',2,1,GETDATE(),'ADMIN',0);	

-- ACM_HABILITATION
-----------------------------
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,42 ,'IHM_CUSTOMER_360' ,'customer-360' ,'IHM'  ,1,GETDATE(),'ADMIN',0);	
 
  INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,42 ,'IHM_CUSTOMER_360_DETAILS' ,'customer-360-details' ,'IHM'  ,1,GETDATE(),'ADMIN',0);
 
  
  INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,42 ,'IHM_CUSTOMER_360' ,'customer-360' ,'CUSTOMER_360'  ,1,GETDATE(),'ADMIN',0);
 
 
-- ACM_HABILITATION EXEMPLE 19
-----------------------------
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,19 ,'IHM_CUSTOMER_360' ,'customer-360' ,'IHM'  ,1,GETDATE(),'ADMIN',0);	
 
  INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,19 ,'IHM_CUSTOMER_360_DETAILS' ,'customer-360-details' ,'IHM'  ,1,GETDATE(),'ADMIN',0);
 
  INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,19 ,'IHM_CUSTOMER_360' ,'customer-360' ,'CUSTOMER_360'  ,1,GETDATE(),'ADMIN',0);
 
 
 -- ACM_HABILITATION_IHM_ROUTE
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
		VALUES('ACM','IHM_SCREENING','screening' ,'page screening' ,1,GETDATE(),'ADMIN',0);
		
----------------------------
-- ACM_HABILITATION_IHM_BUTTON
-----------------------------
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('ACM','NEXT','IHM_SCREENING','NEXT',2,1,GETDATE(),'ADMIN',0);	

-- ACM_HABILITATION
-----------------------------
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,42 ,'IHM_SCREENING' ,'screening' ,'IHM'  ,1,GETDATE(),'ADMIN',0);	
 
   INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
 VALUES('READ','ACM' ,42 ,'IHM_SCREENING' ,'screening' ,'NEXT'  ,1,GETDATE(),'ADMIN',0);