-----------------------------------
----- TABLE : ACM_ADDRESS
-----------------------------------
CREATE TABLE ACM_ADDRESS(
  ID_ACM_ADDRESS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,  
  CUSTOMER_ID BIGINT NOT NULL,
  ADDRESS_1 VARCHAR (512) NULL,
  ADDRESS_2 VARCHAR (512) NULL,
  ADDRESS_3 VARCHAR (512) NULL,
  TOWN_CITY VARCHAR (512) NULL,
  COUNTY VARCHAR (512) NULL,
  STATE VARCHAR (512) NULL,
  POSTAL_CODE VARCHAR (256) NULL,
  COUNTRY VARCHAR (512) NULL,
  REGION VARCHAR (512) NULL,
  ADDRESS1_ID BIGINT NULL,
  ADDRESS2_ID BIGINT NULL,
  ADDRESS3_ID BIGINT NULL,
  TOWN_CITY_ID BIGINT NULL,
  COUNTY_ID BIGINT NULL,
  STATE_ID BIGINT NULL,
  POSTAL_CODE_ID BIGINT NULL,
  COUNTRY_ID BIGINT NULL,
  REGION_ID BIGINT NULL,
  ADDRESS_TYPE_ID BIGINT NULL,
  DATE_MOVED_IN DATETIME NULL,
  DATE_MOVED_OUT DATETIME NULL,
  IS_PRIMARY BIT NOT NULL,
	
  ACM_ENABLED BIT NOT NULL,
  DATE_INSERTION DATETIME NULL,
  INSERT_BY  VARCHAR (256) NULL,
  DATE_LAST_UPDATE DATETIME NULL,
  UPDATED_BY  VARCHAR (256) NULL,
  ACM_VERSION INT NULL
);