-----------------------------------
----- TABLE : ACM_LIST_VALUES_SETTING
-----------------------------------
CREATE TABLE ACM_SETTING_LIST_VALUES (
  ID_ACM_SETTING_LIST_VALUES BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TABLE_ABACUS_NAME  VARCHAR (512) NULL, 
  ID_EXTERN VARCHAR (256) NOT NULL, 
  PARENT_ID BIGINT NULL,
  VALUE_JSON VARCHAR (1000) NULL, 
  
  ACM_ENABLED BIT NOT NULL,
  DATE_INSERTION DATETIME NULL,
  INSERT_BY  VARCHAR (256) NULL,
  DATE_LAST_UPDATE DATETIME NULL,
  UPDATED_BY  VARCHAR (256) NULL,
  ACM_VERSION INT NULL
);

ALTER TABLE ACM_LOAN 
    ADD 
	GUARANTOR_SOURCE_ID INT NULL,
    SOURCE_OF_FUNDS_ID INT NULL,
    REFINANCE_REASON_ID INT NULL,
    DISTRICT_CODE_ID INT NULL,
	INTEREST_FREQ INT NULL,
	INT_PAY_PERIOD_NUM INT NULL;