ALTER TABLE [ACM_SETTING_STATUT_WORKFLOW] ADD [CLIENT] VARCHAR (256) NULL ;
ALTER TABLE [ACM_SETTING_STATUT_WORKFLOW] ADD [BPMN_PROCESS_NAME] VARCHAR (512) NULL ;
ALTER TABLE [ACM_SETTING_STATUT_WORKFLOW] ADD [ORDER_ETAPE_PROCESS] INT NULL ;


----------------------

ALTER TABLE ACM_LOAN ADD [BPMN_PROCESS_NAME] VARCHAR (512) NULL ;
