-- ADD COLUMN GROUP_OWNER and GROUP_OWNER_NAME
ALTER TABLE ACM_LOAN ADD GROUP_OWNER VARCHAR ( 1000 ) NULL ;
ALTER TABLE ACM_LOAN ADD GROUP_OWNER_NAME VARCHAR ( 1000 ) NULL ;

-- ADD HABILITATION UNASSIGNED_LOAN 
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_UNASSIGNED_LOANS' ,'unassigned-loans' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE
--ADD ROUTE HABILITATION UNASSIGNED_LOAN
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
	VALUES('ACM','IHM_UNASSIGNED_LOANS','unassigned-loans' ,'page unassigned loans' ,1,GETDATE(),'ADMIN',0);