-- ADD EXCEPTION REQUEST REJECT REASONS
INSERT INTO [ACM_SETTING_MOTIFS_REJET] ([CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL])
VALUES ( 'REJECT_EXCEPTION_REQUEST', 'REJECT_EXCEPTION_REQUEST_REASON_2', 'Exception request reject reason 2', 'Exception request reject reason 2', 1, GETDATE(), N'ADMIN', NULL, NULL, 0, NULL)

INSERT INTO [ACM_SETTING_MOTIFS_REJET] ([CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL])
VALUES ( 'REJECT_EXCEPTION_REQUEST', 'REJECT_EXCEPTION_REQUEST_REASON_1', 'Exception request reject reason 1', 'Exception request reject reason 2', 1, GETDATE(), N'ADMIN', NULL, NULL, 0, NULL)

-- ADD COLUMN REJECT REASON IN ACM_EXCEPTION_REQUEST
ALTER TABLE ACM_EXCEPTION_REQUEST 
ADD REJECT_NOTE VARCHAR (512)
