INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED,DATE_INSERTION,INSERT_BY,DATE_LAST_UPDATE,UPDATED_BY,ACM_VERSION,DESCRIPTION,CATEGORY,TYPE_VALUE) VALUES
	 (N'LAST_CUACCOUNT_PORTFOLIO_TRANSFERID',N'10',1,'2022-07-18',NULL,'2022-07-18',N'Admin Super (ACM SUPER ADMIN GROUPE)',4,N'last cuAccount portfolio transferred id',N'TECHNICAL',NULL);


	 INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED,DATE_INSERTION,INSERT_BY,DATE_LAST_UPDATE,UPDATED_BY,ACM_VERSION,DESCRIPTION,CATEGORY,TYPE_VALUE) VALUES
	 (N'LAST_BRANCH_CHANGED_ID_SYNCHRONIZED',N'0',1,'2022-07-18',NULL,'2022-07-18',N'Admin Super (ACM SUPER ADMIN GROUPE)',4,N'Last branch changed synchronized id',N'TECHNICAL',NULL);