-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('DBO.ACM_LOAN_HISTORIQUE', 'U') IS NOT NULL
DROP TABLE DBO.ACM_LOAN_HISTORIQUE;
-------------

----- TABLE : ACM_LOAN_HISTORIQUE
CREATE TABLE ACM_LOAN_HISTORIQUE(
    ID_ACM_LOAN_HISTORIQUE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT NOT NULL,
	ACTION VARCHAR (100) NOT NULL,
	DESCRIPTION  VARCHAR (512) NULL,
	DATE_UPDATE DATETIME NOT NULL,
	UPDATED_BY  VARCHAR (256) NOT NULL
	
	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);


-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_DOC_LOAN', 'U') IS NOT NULL
DROP TABLE dbo.ACM_DOC_LOAN;

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_LOAN_DOCUMENTS', 'U') IS NOT NULL
DROP TABLE dbo.ACM_LOAN_DOCUMENTS;
-------------

----- TABLE : ACM_LOAN_DOCUMENTS
 
CREATE TABLE ACM_LOAN_DOCUMENTS(
    ID_ACM_LOAN_DOCUMENTS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT NOT NULL,
	ID_DOCUMENT_GED VARCHAR (256) NULL,
    TITRE  VARCHAR (512) NOT NULL,
    DESCRIPTION  VARCHAR (1000) NULL,
    AUTEUR VARCHAR (256) NULL,
    DATE_CREATION DATE NULL,
    TYPE_MIME VARCHAR (50) NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	
	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);