ALTER TABLE ACM_LOAN
    ADD 
        LOANPRODUCT_DESCRIPTION VARCHAR (512) NULL,
        LOANPRODUCT_CODE VARCHAR (256) NULL,
		CUSTOMER_NAME VARCHAR (256) NULL,
		AMOUNT DECIMAL NULL,
        CURRENCY_SYMBOL VARCHAR (10) NULL,
		CURRENCY_DECIMALPLACES INT NULL,
		APPLYDATE DATE NULL,
        ACCOUNTPORTFOLIO_CODE VARCHAR (256) NULL,
		ACCOUNTPORTFOLIO_DESCRIPTION VARCHAR (256) NULL;
		
ALTER TABLE [ACM].[dbo].[ACM_LOAN]
ALTER COLUMN [LOANPRODUCT_DESCRIPTION] VARCHAR (512) COLLATE Arabic_CI_AI_KS_WS;

ALTER TABLE [ACM].[dbo].[ACM_LOAN]
ALTER COLUMN [CUSTOMER_NAME] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;

ALTER TABLE [ACM].[dbo].[ACM_LOAN]
ALTER COLUMN [ACCOUNTPORTFOLIO_DESCRIPTION] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;
