-------------------
----- TABLE : ACM_USERS
IF OBJECT_ID('dbo.ACM_USERS', 'U') IS NOT NULL
DROP TABLE dbo.ACM_USERS;

-------------------
----- TABLE : ACM_USERS 
CREATE TABLE ACM_USERS(   
	USERNAME VARCHAR (256) NOT NULL PRIMARY KEY,   
	PASSWORD VARCHAR (256) NOT NULL,
	ACCOUNT_PORTFOLIO_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE PORTFOLIO COTÉ ABACUS
	USER_EXTERN_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE USER COTÉ ABACUS
	USER_PROFIL_ID BIGINT NOT NULL, --- 0 : PAR DEFAULT PAS DE PROFIL COTÉ ABACUS
	RESPONSABLE_ID BIGINT NOT NULL , --- 0 : PAS DE RESPONSABLE 

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
	);
	
-------------------
----- TABLE : OAUTH_CLIENT_DETAILS 
create table oauth_client_details (
    client_id varchar(256) primary key,
    resource_ids varchar(256),
    client_secret varchar(256),
    scope varchar(256),
    authorized_grant_types varchar(256),
    web_server_redirect_uri varchar(256),
    authorities varchar(256),
    access_token_validity integer,
    refresh_token_validity integer,
    additional_information varchar(4096),
    autoapprove varchar(256)
);

-------------------
----- TABLE : OAUTH_ACCESS_TOKEN  
create table oauth_access_token (
  token_id VARCHAR(256),
  token VARBINARY(5000),
  authentication_id VARCHAR(256) PRIMARY KEY,
  user_name VARCHAR(256),
  client_id VARCHAR(256),
  authentication VARBINARY(5000),
  refresh_token VARCHAR(256)
);

-------------------
----- TABLE : OAUTH_REFRESH_TOKEN  
create table oauth_refresh_token (
  token_id VARCHAR(256) PRIMARY KEY,
  token VARBINARY(5000),
  authentication VARBINARY(5000)
);


IF OBJECT_ID('DBO.ACM_GROUPE', 'U') IS NOT NULL
	DROP TABLE DBO.ACM_GROUPE;

-------------------
----- TABLE : ACM_GROUPE 
CREATE TABLE ACM_GROUPE(   
	ID_ACM_GROUPE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE VARCHAR (256) NOT NULL,
	LIBELLE VARCHAR (100) NOT NULL,
	DESCRIPTION  VARCHAR (512) NULL,
			
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);

-------------------
-------------------

IF OBJECT_ID('DBO.ACM_USERS_GROUPE', 'U') IS NOT NULL
	DROP TABLE DBO.ACM_USERS_GROUPE;

-------------------
----- TABLE : ACM_USERS_GROUPE 
CREATE TABLE ACM_USERS_GROUPE(   
	ID_ACM_GROUPE BIGINT NOT NULL,
	USERNAME VARCHAR (256) NOT NULL,
    PRIMARY KEY (ID_ACM_GROUPE, USERNAME),
    FOREIGN KEY (ID_ACM_GROUPE) REFERENCES ACM_GROUPE (ID_ACM_GROUPE),
    FOREIGN KEY (USERNAME) REFERENCES ACM_USERS (USERNAME)	
);

-------------------
-------------------

IF OBJECT_ID('DBO.ACM_HABILITATION', 'U') IS NOT NULL
	DROP TABLE DBO.ACM_HABILITATION;

-------------------
----- TABLE : ACM_HABILITATION 
CREATE TABLE ACM_HABILITATION(   
	ID_ACM_HABILITATION BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	ACTIONS  VARCHAR (512) NOT NULL,
	CLIENT VARCHAR (256) NOT NULL,
	GROUPE_ID BIGINT NOT NULL,
	ACM_HABILITATION VARCHAR (512) NOT NULL,
	ACM_WEB_ROUTE VARCHAR (512) NOT NULL,
	VALUE BIT NOT NULL,
			
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);