-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_SETTING_PROCESS_LEVEL', 'U') IS NOT NULL
DROP TABLE dbo.ACM_SETTING_PROCESS_LEVEL;

IF OBJECT_ID('dbo.ACM_SETTING_LEVEL', 'U') IS NOT NULL
DROP TABLE dbo.ACM_SETTING_LEVEL;
-------------

----- TABLE : ACM_SETTING_LEVEL
 
CREATE TABLE ACM_SETTING_LEVEL(
    ID_ACM_SETTING_LEVEL BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE VARCHAR (256) NOT NULL,
	TITLE VARCHAR (256) NOT NULL,
	DESCRIPTION VARCHAR (256) NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);


CREATE TABLE ACM_SETTING_PROCESS_LEVEL(
    ID_ACM_SETTING_PROCESS_LEVEL BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_PRODUCT BIGINT NOT NULL,
	AMOUNT BIGINT NOT NULL,
	DESCRIPTION VARCHAR (256) NULL,
	ID_ACM_SETTING_LEVEL BIGINT NOT NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	
	FOREIGN KEY (ID_ACM_SETTING_LEVEL) REFERENCES ACM_SETTING_LEVEL (ID_ACM_SETTING_LEVEL)
);