-------------
----- TABLE : ACM_EXPENSES_TYPES
create table dbo.ACM_EXPENSES_TYPES (
    ID_ACM_EXPENSES_TYPES BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE VARCHAR (256),
	LIBEL VARCHAR (256),
	DESCRIPTION VARCHAR (256),
	DOCUMENT_ID BIGINT,
	DOCUMENT_LIBEL VARCHAR(250),

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);

-------------
----- TABLE : ACM_EXPENSES_TYPES
create table dbo.ACM_EXPENSES_LIMITS (
    ID_ACM_EXPENSES_LIMITS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_BRANCH BIGINT NOT NULL,
	ID_EXPENSES_TYPE BIGINT NOT NULL,
	LIMIT BIGINT,
	RESTLIMIT BIGINT,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);

---------TABLE : EXPENSES
CREATE TABLE ACM_EXPENSES (
    ID_EXPENSES BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_EXPENSES_TYPE BIGINT NOT NULL,
	ID_BRANCH BIGINT,
	BRANCH_DESCRIPTION VARCHAR (256) NULL,
	EXPENSES_AMOUNT BIGINT NULL,
	EXPENSES_OWNER  VARCHAR (256),
	TELLER VARCHAR (256),
	EXPENSES_DESCRIPTION  VARCHAR (256),
	STATUT INT,
	BALANCE BIGINT,
	EXPENSES_TYPE_LIBELLE VARCHAR (256),
	TELLER_NAME VARCHAR (256),
	OWNER_NAME VARCHAR (256),
	EXPENSES_REJECT_NOTE VARCHAR (512),
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT,
	APPLYDATE DATE NULL
);

----------- HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
VALUES('ACM','IHM_EXPENSES_SETTING','expenses-settings' ,'page Expenses Setting' ,1,GETDATE(),'ADMIN',0);
		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
VALUES('ACM','IHM_EXPENSES_LIST','expenses-list' ,'page Expenses List' ,1,GETDATE(),'ADMIN',0);
		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
VALUES('ACM','IHM_EXPENSES_INFO','expenses-info' ,'page Expenses Info' ,1,GETDATE(),'ADMIN',0);

 
		
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_SETTING' ,'expenses-settings' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE	 

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_LIST' ,'expenses-list' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_LIST' ,'expenses-list' ,'ADD'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_INFO' ,'expenses-info' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_INFO' ,'expenses-info' ,'ACCEPT'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EXPENSES_INFO' ,'expenses-info' ,'REJECT'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE
-------------
----- TABLE : ACM_ENVIRONNEMENT
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION], [DESCRIPTION], [CATEGORY]) 
VALUES ('CURRENCY', 'EGP', 1, '2021-07-01', 0,'SYSTEM CURRENCTY','FUNCTIONAL');  
