IF OBJECT_ID('dbo.ACM_DOCUMENTS_GED', 'U') IS NOT NULL
DROP TABLE dbo.ACM_DOCUMENTS_GED;
-------------
----- TABLE : ACM_DOCUMENTS_GED
CREATE TABLE ACM_DOCUMENTS_GED(  
    ID_ACM_DOCUMENTS_GED  BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_DOCUMENTS BIGINT NOT NULL,
    ID_CUSTOMER BIGINT NOT NULL,
    ID_LOAN BIGINT NULL,
	DOCUMENT_GED varBinary(MAX) NOT NULL,
	
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);