ALTER TABLE ACM_LOAN 
    ADD 
        INITIAL_PAYMENT_DATE DATE NULL,
        NORMAL_PAYMENT BIGINT NULL,
        IGNORE_ODD_DAYS BIT NULL,
        PERIODS_DEFERRED INT NULL,
        CALCULATE_INITIAL_PAYMENT_DATE BIT NULL,
        TERM_PERIOD_ID BIGINT NULL;
        