-- default groupe
INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES('ACM_DEFAULT_GROUP',' ACM Default Group','Groupe default',1,GETDATE(),'ADMIN',0);
     
--------------

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CONSEILLER_CREDIT','Conseiller Crédit','Groupe pour Conseiller Crédit',1,GETDATE(),'ADMIN',0,1);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CHARGEE_CLIENTELE','Chargée Clientèle','Groupe pour Chargée Clientèle',1,GETDATE(),'ADMIN',0,2);   

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CONSEILLER_ACCOMPAGNEMENT','Conseiller Accompagnement','Groupe pour Conseiller Accompagnement',1,GETDATE(),'ADMIN',0,3);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTEUR_AGENCE','Directeur d''Agence','Groupe pour Directeur d''Agence',1,GETDATE(),'ADMIN',0,4);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DG','DG','Groupe pour DG',1,GETDATE(),'ADMIN',0,5);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('ADMINISTRATEUR','Administrateur','Groupe pour Administrateur',1,GETDATE(),'ADMIN',0,9);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('AUDITEUR','Auditeur','Groupe pour Auditeur',1,GETDATE(),'ADMIN',0,10);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('BACK_OFFICE','Back Office','Groupe pour Back Office',1,GETDATE(),'ADMIN',0,21);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CHARGE_RECOUVREMENT','Chargé Recouvrement','Groupe pour Chargé Recouvrement',1,GETDATE(),'ADMIN',0,22);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DSI','DSI','Groupe pour DSI',1,GETDATE(),'ADMIN',0,24);
     
     

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('ORGANISATION','Organisation','Groupe pour Organisation',0,GETDATE(),'ADMIN',0,11);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTRICE_AGENCE_IBN_KHALDOUN','Directrice Agence Ibn Khaldoun','Groupe pour Directrice Agence Ibn Khaldoun',0,GETDATE(),'ADMIN',0,12);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('AGENCE_IBN_KHALLED','Agence Ibn Khalled','Groupe pour Agence Ibn Khalled',0,GETDATE(),'ADMIN',0,13);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CHARGEE_CLIENTELE_AGENCE','Chargée Clientèle agence','Groupe pour Chargée Clientèle agence',0,GETDATE(),'ADMIN',0,14);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTEUR_AGENCE_SILIANA','Directeur Agence Siliana','Groupe pour Directeur Agence Siliana',0,GETDATE(),'ADMIN',0,15);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTEUR_AGENCE_KEF','Directeur Agence Kef','Groupe pour Directeur Agence Kef',0,GETDATE(),'ADMIN',0,16);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTEUR_AGENCE_KEF','Directeur Agence Kef','Groupe pour Directeur Agence Kef',0,GETDATE(),'ADMIN',0,17);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('CHARGEE_CLIENT','Chargée Client','Groupe pour Chargée Client',0,GETDATE(),'ADMIN',0,18);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('ADMFR','ADMFR','Groupe pour ADMFR',0,GETDATE(),'ADMIN',0,19);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('MOBILE_BANKING','Mobile Banking','Groupe pour Mobile Banking',0,GETDATE(),'ADMIN',0,20);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('COMPTABLE','Comptable','Groupe pour Comptable',0,GETDATE(),'ADMIN',0,6);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTEUR_OPERATIONS','Directeur Opérations','Groupe pour Directeur Opérations',0,GETDATE(),'ADMIN',0,7);

INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],USER_PROFILE_ID_EXTERN)
     VALUES('DIRECTION_GENERALE','Direction Générale','Groupe pour Direction Générale',0,GETDATE(),'ADMIN',0,8);
     