-- BD : DEV
ALTER TABLE ACM_DOCUMENTS  DROP CONSTRAINT  FK__ACM_DOCUM__ID_AC__25924E90
-- BD : RECETTE
ALTER TABLE ACM_DOCUMENTS  DROP CONSTRAINT FK__ACM_DOCUM__ID_AC__5629CD9C

ALTER TABLE ACM_DOCUMENTS DROP COLUMN ID_ACM_LOAN 

ALTER TABLE ACM_DOCUMENTS ADD ID_LOAN BIGINT NULL;

ALTER TABLE ACM_DOCUMENTS ADD ACCOUNT_NUMBER_EXTERN VARCHAR (256);

ALTER TABLE ACM_DOCUMENTS ADD CUSTOMER_NAME VARCHAR (512) NULL;
ALTER TABLE ACM_DOCUMENTS ALTER COLUMN [CUSTOMER_NAME] VARCHAR (512) COLLATE Arabic_CI_AI_KS_WS; 


