----- TABLE : ACM_ENVIRONNEMENT
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION], [DESCRIPTION], [CATEGORY]) 
VALUES ('CRON_EXPRESSION_EXPENSES', '0 0/1 * * * ?', 1, '2021-07-12', 0,'SYSTEM CURRENCTY','TECHNICAL');  