UPDATE ACM_PRODUCT SET 
ISCORE_NUM_DAYS_EXPIRY_CHECK=30 ,
ISCORE_MIN_SCORE=500 ,
ISCORE_MAX_SCORE=625 ,
ISCORE_MIN_ACTIVE_LOANS=3 ,
ISCORE_MIN_NUM_DAYS_DUE=90,
ISCORE_MAX_ACTIVE_LOANS=5 ,
ISCORE_MAX_NUM_DAYS_DUE=120
WHERE code ='MEL 1';

UPDATE ACM_PRODUCT SET 
ISCORE_NUM_DAYS_EXPIRY_CHECK=30 ,
ISCORE_MIN_SCORE=500 ,
ISCORE_MAX_SCORE=625 ,
ISCORE_MIN_ACTIVE_LOANS=3 ,
ISCORE_MIN_NUM_DAYS_DUE=90,
ISCORE_MAX_ACTIVE_LOANS=5 ,
ISCORE_MAX_NUM_DAYS_DUE=120
WHERE code ='MEL 2';

