
-- ALTER TABLE ACM_3RD_PARTY_HISTORIQUE
ALTER TABLE ACM_3RD_PARTY_HISTORIQUE
ADD 
SCORE INT NULL,
ACTIVE_LOANS INT NULL,
MAX_NUM_DAYS_DUE INT NULL,
QUERY_DATE DATETIME NULL,
REPORT_ISCORE varBinary(MAX)  NULL;

-- ALTER TABLE ACM_PRODUCT
ALTER TABLE ACM_PRODUCT
ADD
ISCORE_NUM_DAYS_EXPIRY_CHECK INT NULL,
ISCORE_MAX_SCORE INT NULL,
ISCORE_MAX_ACTIVE_LOANS INT NULL,
ISCORE_MAX_NUM_DAYS_DUE INT NULL,
AML_CHECK_POURCENTAGE decimal(9,6) NULL;

ALTER TABLE ACM_PRODUCT
ADD 
ISCORE_MIN_SCORE INT NULL,
ISCORE_MIN_ACTIVE_LOANS INT NULL,
ISCORE_MIN_NUM_DAYS_DUE INT NULL;
