  
  -- ADD REVIEW AGREEMENTS REASON 
  INSERT INTO [ACM_SETTING_MOTIFS_REJET] ([CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL])
  VALUES ( 'REVIEW_AGREEMENTS', 'REVIEW_AGREEMENTS_REASON_2', 'Review agreement reason 2', 'Review agreement reason 2', 1, GETDATE(), N'ADMIN', NULL, NULL, 0, NULL)

   INSERT INTO [ACM_SETTING_MOTIFS_REJET] ([CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL])
  VALUES ( 'REVIEW_AGREEMENTS', 'REVIEW_AGREEMENTS_REASON_1', 'Review agreement reason 1', 'Review agreement reason 1', 1, GETDATE(), N'ADMIN', NULL, NULL, 0, NULL)