-- insert client name --
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('REPORT_CLIENT_NAME', 'TAMKEEN', 1, '2021-04-05', 0, 'FUNCTIONAL');