-- ADD COLUMN INCENTIVE_REPAYMENT,  INCENTIVE_REGESTRATION, INCENTIVE_OPERATION, INCENTIVE_LEGAL  IN ACM_PRODUCT_CATEGORY
ALTER TABLE ACM_PRODUCT_CATEGORY ADD 
INCENTIVE_REPAYMENT BIT null,
INCENTIVE_REGESTRATION BIT null,
INCENTIVE_OPERATION BIT null,
INCENTIVE_LEGAL BIT null;

