
alter table acm_habilitation add DESCRIPTION VARCHAR(512)

update ACM_HABILITATION set description = 'DASHBOARD SCREEN' where ACM_HABILITATION = 'HOME'
update ACM_HABILITATION set description = 'COMPLETE LOAN DATA SCREEN (EDIT CUSTOMER)' where ACM_HABILITATION = 'IHM_LOAN_DETAILS'
update ACM_HABILITATION set description = 'FIELD VISIT SCREEN' where ACM_HABILITATION = 'IHM_FIELD_VISIT'
update ACM_HABILITATION set description = 'GUARANTOR SCREEN' where ACM_HABILITATION = 'IHM_CHECK_GUARANTOR'
update ACM_HABILITATION set description = 'COLLATERAL SCREEN' where ACM_HABILITATION = 'IHM_CHECK_COLLATERAL'
update ACM_HABILITATION set description = 'UPLOAD DOCUMENT SCREEN' where ACM_HABILITATION = 'IHM_UPLOAD_DOCUMENT'
update ACM_HABILITATION set description = 'FINANCIAL ANALYSIS SCREEN' where ACM_HABILITATION = 'IHM_FINANCIAL_ANALYSIS'
update ACM_HABILITATION set description = 'APPROVAL SCREEN' where ACM_HABILITATION = 'IHM_LOAN_APPROVAL'
update ACM_HABILITATION set description = 'CUSTOMER DECISION SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_DECISION'
update ACM_HABILITATION set description = 'CALENDAR SCREEN' where ACM_HABILITATION = 'IHM_CALENDAR'

update ACM_HABILITATION set description = 'TASK SCREEN' where ACM_HABILITATION = 'IHM_TASK'
update ACM_HABILITATION set description = 'ADD DOCUMENT SCREEN' where ACM_HABILITATION = 'IHM_ADD_DOCUMENT'
update ACM_HABILITATION set description = 'UPLOAD SIGNED AGREEMENT SCREEN' where ACM_HABILITATION = 'IHM_UPLOAD_SIGNED_AGREEMENT'
update ACM_HABILITATION set description = 'NOTIFICATION SCREEN' where ACM_HABILITATION = 'IHM_NOTIFICATIONS'
update ACM_HABILITATION set description = 'FIND DOCUMENT SCREEN' where ACM_HABILITATION = 'IHM_FIND_DOCUMENT'
update ACM_HABILITATION set description = 'REVIEW SCREEN (RISK/AUDIT)' where ACM_HABILITATION = 'IHM_LOAN_REVIEW'


update ACM_HABILITATION set description = 'LOAN ASSIGNEMENT SCREEN' where ACM_HABILITATION = 'IHM_LOAN_ASSIGN'
update ACM_HABILITATION set description = 'SETTING SCREEN' where ACM_HABILITATION = 'IHM_SETTING'
update ACM_HABILITATION set description = 'ONLINE APPLICATION SCREEN' where ACM_HABILITATION = 'IHM_ONLINE_APPLICATION'
update ACM_HABILITATION set description = 'ONLINE APPLICATION DETAIL SCREEN' where ACM_HABILITATION = 'IHM_ONLINE_APPLICATION_INFO'
update ACM_HABILITATION set description = 'ADD CUSTOMER SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_MANAGEMENT'
update ACM_HABILITATION set description = 'ANALYTICS SCREEN' where ACM_HABILITATION = 'IHM_ANALYTICS'


update ACM_HABILITATION set description = 'ADD LOAN SCREEN' where ACM_HABILITATION = 'IHM_LOAN_MANAGEMENT'
update ACM_HABILITATION set description = 'CUSTOMER 360 IN THE MENU' where ACM_HABILITATION = 'IHM_CUSTOMER_360'
update ACM_HABILITATION set description = 'CUSTOMER 360 DETAIL SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_360_DETAILS'
update ACM_HABILITATION set description = 'CUSTOMER GROUPE WORKFLOW SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_GROUPE'
update ACM_HABILITATION set description = 'SCREENING SCREEN' where ACM_HABILITATION = 'IHM_SCREENING'
update ACM_HABILITATION set description = 'EDIT CUSTOMER IN THE MENU' where ACM_HABILITATION = 'IHM_CUSTOMER_EDIT'


update ACM_HABILITATION set description = 'CUSTOMER LIST SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_LIST'
update ACM_HABILITATION set description = 'CUSTOMER MESSAGE SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_MESSAGE'
update ACM_HABILITATION set description = 'REPPORT LIST SCREEN' where ACM_HABILITATION = 'IHM_REPPORTS_LIST'
update ACM_HABILITATION set description = 'EDIT CUSTOMER IN THE MENU' where ACM_HABILITATION = 'IHM_CUSTOMER_EDIT_PAGE'
update ACM_HABILITATION set description = 'COMPLETE LOAN DATA SCREEN (EDIT LOAN)' where ACM_HABILITATION = 'COMPLETE_LOAN_DETAILS'
update ACM_HABILITATION set description = 'ACTION BUTTON IN WORKLFOW' where ACM_HABILITATION = 'IHM_ACTIONS'

update ACM_HABILITATION set description = 'EXPENSES SETTING SCREEN' where ACM_HABILITATION = 'IHM_EXPENSES_SETTING'
update ACM_HABILITATION set description = 'EXPENSES LIST SCREEN' where ACM_HABILITATION = 'IHM_EXPENSES_LIST'
update ACM_HABILITATION set description = 'EXPENSES INFO SCREEN' where ACM_HABILITATION = 'IHM_EXPENSES_INFO'
update ACM_HABILITATION set description = 'AML SETTING SCREEN' where ACM_HABILITATION = 'IHM_SETTING_AML'
update ACM_HABILITATION set description = 'MEZA CARD SETTING SCREEN' where ACM_HABILITATION = 'IHM_MEZA_CARD_SETTING'
update ACM_HABILITATION set description = 'MEZA CARD ACTIVATING SCREEN' where ACM_HABILITATION = 'IHM_MEZA_CARD_ACTIVATE'

update ACM_HABILITATION set description = 'MEZA CARD CHECK SCREEN' where ACM_HABILITATION = 'IHM_MEZA_CARD_CHECK'
update ACM_HABILITATION set description = 'AML CHECK SCREEN' where ACM_HABILITATION = 'IHM_CUSTOMER_AML_CHECK'
update ACM_HABILITATION set description = 'UNASSIGNED LOAN SCREEN' where ACM_HABILITATION = 'IHM_UNASSIGNED_LOANS'
update ACM_HABILITATION set description = 'ISSUANCE REPAYEMENT INCENTIVE SCREEN' where ACM_HABILITATION = 'IHM_ISSUANCE_REPAYEMENT_INCENTIVE'
update ACM_HABILITATION set description = 'REGISTRATION INCENTIVE SCREEN' where ACM_HABILITATION = 'IHM_REGISTRATION_INCENTIVE'
update ACM_HABILITATION set description = 'OPERATION INCENTIVE SCREEN' where ACM_HABILITATION = 'IHM_OPERATION_INCENTIVE'
update ACM_HABILITATION set description = 'LEGAL INCENTIVE SCREEN' where ACM_HABILITATION = 'IHM_LEGEL_INCENTIVE'
update ACM_HABILITATION set description = 'RUN INCENTIVE SCREEN' where ACM_HABILITATION = 'IHM_RUN_INCENTIVE'

 