 ALTER TABLE ACM_LOAN
 ADD OTHER_INFORMATIONS varchar(2000);

 --add ihm and habilitation to button execute api 
 
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
		VALUES('ACM','IHM_EXECUTE_API','EXECUTE_API' ,'EXECUTE_API' ,1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','EXECUTE_API','IHM_EXECUTE_API','EXECUTE API',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_EXECUTE_API';

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_EXECUTE_API' ,'execute-api' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'EXECUTE API THIRD PARTY' from ACM_GROUPE