
alter table ACM_LOAN
drop column CUSTOMER_ID_REIS ; 

alter table ACM_CUSTOMER
drop column SEARCH_QUERY_ID ; 

delete from ACM_ENVIRONNEMENT where  ACM_ENVIRONNEMENT_KEY = 'VNEURON_SYSTEM_NAME';
delete from ACM_ENVIRONNEMENT where  ACM_ENVIRONNEMENT_KEY = 'VNEURON_SYSTEM_ID';

ALTER TABLE  ACM_3RD_PARTY_HISTORIQUE ADD SEARCH_QUERY_ID bigint NULL;
ALTER TABLE  ACM_3RD_PARTY_HISTORIQUE ADD CUSTOMER_ID_REIS bigint NULL;

insert into ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE , ACM_ENABLED ) values ('VNEURON_API_SYSTEM_NAME','SANAD',1)  , 
																							 ('VNEURON_API_SYSTEM_ID','15',1) 	
	  


 