 ALTER TABLE ACM_PRODUCT_DETAILS
 ADD GREEN_RATE Integer ;

  ALTER TABLE ACM_PRODUCT_DETAILS
 ADD ORANGE_RATE integer;

  ALTER TABLE ACM_PRODUCT_DETAILS
 ADD RED_RATE Integer ;

 ALTER TABLE ACM_3RD_PARTY_HISTORIQUE
 ADD RISK_LEVEL varchar(22);