 --yakeen
 insert into ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED)
 values('YAKEEN_API_REQUEST_URL','https://783c9b54-b9fa-487c-9982-dc4f2a93c36f.mock.pstmn.io',1),
       ('YAKEEN_API_REQUEST_SERVICE_IDENTIFIER','390cda69-046c-4251-a89c-b9a4edb8e335',1),
       ('YAKEEN_API_REQUEST_OPERATOR_ID','100001010',1),
	   ('YAKEEN_API_REQUEST_APP_ID','app-id',1),
	   ('YAKEEN_API_REQUEST_APP_KEY','app-key',1),
	   ('YAKEEN_API_REQUEST_USAGE_CODE','USC-00002',1),
	   ('YAKEEN_API_REQUEST_USERNAME','abc',1),
	   ('YAKEEN_API_REQUEST_PASSWORD','abcd',1);

--MobiShastra (otp)
insert into ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED)
values('MOBISHASTRA_API_REQUEST_USER','user',1),
('MOBISHASTRA_API_REQUEST_SENDER','sender',1),
('MOBISHASTRA_API_REQUEST_PWD','pwd',1),
('MOBISHASTRA_API_REQUEST_LANGUAGE','language',1),
('MOBISHASTRA_API_REQUEST_URL','https://28847415-5334-4999-93dc-04f788533132.mock.pstmn.io',1);

--Payment Api
insert into ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED)
values('PAYMENT_SANAD_API_REQUEST_URL','https://3323f6a5-9a9b-4531-aa61-1592dcfa1e34.mock.pstmn.io',1);


