CREATE TABLE [dbo].[ACM_SETTING_DOC_TYPE](
	[ID_ACM_SETTING_DOC_TYPE] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](256) NOT NULL,
	[LIBELLE] [varchar](512) NULL,
	[DESCRIPTION] [varchar](512) NULL,
	[CATEGORIE] [smallint] NOT NULL,
	[UNIQUENESS] [bit] NULL,
	[DATE_DEBUT] [date] NULL,
	[DATE_FIN] [date] NULL,
	
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [date] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ACM_SETTING_DOC_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACM_SETTING_DOC_TYPE] ADD  DEFAULT ((1)) FOR [ACM_ENABLED]
GO
