IF OBJECT_ID('dbo.ACM_LOAN_APPROVAL_HISTORIQUE', 'U') IS NOT NULL
DROP TABLE dbo.ACM_LOAN_APPROVAL_HISTORIQUE;

CREATE TABLE ACM_LOAN_APPROVAL_HISTORIQUE(
    ID_ACM_LOAN_APPROVAL_HISTORIQUE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT NOT NULL,
	
	APPROVAL_DATE DATETIME NOT NULL,
	APPROVAL_AMOUNT BIGINT NOT NULL,
	APPROVAL_DESICION INT NOT NULL,
	APPROVAL_DESICION_LABEL VARCHAR (256) NOT NULL,
	APPROVAL_NOTE  VARCHAR (512) NOT NULL,
    APPROVAL_LEVEL INT NOT NULL,
	APPROVAL_LEVEL_LABEL VARCHAR (256) NOT NULL,
	APPROVED_BY  VARCHAR (256) NULL,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL

	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);