CREATE TABLE [dbo].[ACM_SETTING_DOC_PRODUCT](
	[ID_ACM_SETTING_DOC_PRODUCT] [bigint] IDENTITY(1,1) NOT NULL,
	[PRODUCT_ID] [int] NOT NULL,
	[ID_ACM_SETTING_DOC_TYPE] [bigint] NOT NULL,
	[MANDATORY] [bit] NOT NULL,
	[DATE_DEBUT] [date] NULL,
	[DATE_FIN] [date] NULL,
	
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [date] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ACM_SETTING_DOC_PRODUCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ACM_SETTING_DOC_PRODUCT] ADD  DEFAULT ((1)) FOR [ACM_ENABLED]
GO

 ALTER TABLE [dbo].[ACM_SETTING_DOC_PRODUCT]
   ADD CONSTRAINT FK_ID_ACM_SETTING_DOC_TYPE FOREIGN KEY (ID_ACM_SETTING_DOC_TYPE)
      REFERENCES [ACM_SETTING_DOC_TYPE] ([ID_ACM_SETTING_DOC_TYPE])