INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','UPDATE_ALL','IHM_CUSTOMER_LIST','UPDATE ALL CUSTOMER',
ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0 
from ACM_HABILITATION_IHM_ROUTE 
where CODE_IHM_ROUTE = 'IHM_CUSTOMER_LIST'

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], DESCRIPTION)
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CUSTOMER_LIST' ,'customer-list' ,'UPDATE_ALL'  ,1,GETDATE(),'ADMIN',0,'CUSTOMER LIST SCREEN' from ACM_GROUPE



