-- Rename table ACM_COLLECTION_THIRD_PARTY to ACM_THIRD_PARTY
EXEC sp_rename 'ACM_COLLECTION_THIRD_PARTY', 'ACM_THIRD_PARTY';

-- Rename column ID_ACM_THIRD_PARTY_LEGAL_COLLECTION to ID_ACM_THIRD_PARTY
EXEC sp_rename N'ACM_THIRD_PARTY.ID_ACM_THIRD_PARTY_LEGAL_COLLECTION' , N'ID_ACM_THIRD_PARTY', 'COLUMN';

-- Add new columns
ALTER TABLE ACM_THIRD_PARTY ADD [TYPE] varchar(512) NULL;
ALTER TABLE ACM_THIRD_PARTY ADD [STATUT] varchar(512) NULL;
ALTER TABLE ACM_THIRD_PARTY ADD [PAYS] varchar(512) NULL;
ALTER TABLE ACM_THIRD_PARTY ADD [VILLE] varchar(512) NULL;
ALTER TABLE ACM_THIRD_PARTY ADD [CODE_POSTAL] bigint NULL;
ALTER TABLE ACM_THIRD_PARTY ADD [NUMERO_RNE] bigint NULL;

-- ADD HABILITATION add new party
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_ADD_THIRD_PARTY' ,'add-setting-third-party' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

-- ADD ROUTE add new party
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])  
VALUES('ACM','IHM_ADD_THIRD_PARTY','add-setting-third-party' ,'page add new party' ,1,GETDATE(),'ADMIN',0);

-- Set Id IHM route 
UPDATE  ACM_HABILITATION set ID_ACM_HABILITATION_IHM_ROUTE  = 50077 where ACM_HABILITATION = 'IHM_ADD_THIRD_PARTY';

-- ADD HABILITATION edit party
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_EDIT_THIRD_PARTY' ,'setting-third-party' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

--ADD ROUTE edit party
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])  
VALUES('ACM','IHM_EDIT_THIRD_PARTY','setting-third-party' ,'page edit party' ,1,GETDATE(),'ADMIN',0);

-- Set Id IHM route 
UPDATE  ACM_HABILITATION set ID_ACM_HABILITATION_IHM_ROUTE  = 50079 where ACM_HABILITATION = 'IHM_EDIT_THIRD_PARTY'

-- ADD HABILITATION edit party
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'UPDATE','ACM' ,ID_ACM_GROUPE ,'IHM_EDIT_THIRD_PARTY' ,'setting-third-party' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

-- Set Id IHM route 
UPDATE  ACM_HABILITATION set ID_ACM_HABILITATION_IHM_ROUTE  = 50079 where ACM_HABILITATION = 'IHM_EDIT_THIRD_PARTY';

-- Button update habilitation

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'EXECUTE','ACM' ,ID_ACM_GROUPE ,'IHM_EDIT_THIRD_PARTY' ,'setting-third-party' ,'UPDATE'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE
-- Set Id IHM route
UPDATE  ACM_HABILITATION set ID_ACM_HABILITATION_IHM_ROUTE  = 50079 where ACM_HABILITATION = 'IHM_EDIT_THIRD_PARTY' AND ACTIONS='EXECUTE';
