DROP TABLE CLASS_DETAILS;
DROP TABLE CLASS_TYPE;

CREATE TABLE SIMAH_CLASS_TYPE (
	ID_SIMAH_CLASS_TYPE BIGINT NOT NULL PRIMARY KEY,
    CLASS_LABEL NVARCHAR(255) NOT NULL,
    CLASS_DESCRIPTION NVARCHAR(255),
);

CREATE TABLE SIMAH_CLASS_DETAILS(
    ID_SIMAH_CLASS_DETAILS BIGINT IDENTITY(1,1) PRIMARY KEY,
    SALARY_FROM DECIMAL(18, 2),
    SALARY_TO DECIMAL(18, 2),
    RATE BIGINT NOT NULL ,
    ID_CLASS_TYPE BIGINT,
    FOREIGN KEY (ID_CLASS_TYPE) REFERENCES SIMAH_CLASS_TYPE(ID_SIMAH_CLASS_TYPE)
);

INSERT INTO SIMAH_CLASS_TYPE (ID_SIMAH_CLASS_TYPE,CLASS_LABEL,CLASS_DESCRIPTION)
VALUES
   (1,'Class1', 'لا توجد أي التزامات تمويلية'),
    (2,'Class2', 'لا توجد أي التزامات تمويلية (متقاعد)'),
    (3,'Class3', 'وجود التزام تمويلي شخصي'),
    (4,'Class4', 'وجود التزام عقاري غير مدعوم'),
    (5,'Class5', 'وجود التزام عقاري مدعوم'),
    (6,'Class6', 'وجود التزامات تمويلية');
   
INSERT INTO SIMAH_CLASS_DETAILS (SALARY_FROM,SALARY_TO,RATE,ID_CLASS_TYPE)
VALUES
   (3500.00,0.00,33,1),
   (3500.00,0.00,25,2),
   (3500.00,0.00,45,3),
   (0.00,15000.00,55,4),
   (15000.00,0.00,65,4),
   (3500.00,0.00,65,5),
   (25000.00,0.00,70,6);

  
ALTER TABLE ACM_LOAN
ADD MAX_INSTALLMENT DECIMAL(18, 2);