  INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY, ACM_ENVIRONNEMENT_VALUE, ACM_ENABLED)
 VALUES ('ISSUE_DATE', 14,1)

 INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY, ACM_ENVIRONNEMENT_VALUE, ACM_ENABLED)
 VALUES ('INITIAL_PAYMENT', 20,1)