CREATE TABLE [dbo].[ACM_TEMPLATE_SMS](
	[ID_ACM_TEMPLATE_SMS]  BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[SMS_EVENT_CODE] [varchar](100) NULL,
	[MESSAGE_BODY] [varchar](500) NULL,
	[DATE_ENVOI] [date] NULL,
    [CATEGORY] [varchar](50)
	
)


CREATE TABLE ACM_MESSAGE_DETAILS
(
    [ID_MESSAGE_DETAILS] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [MESSAGE_BODY] [varchar](4000) NULL,
    [LIST_ID] [varchar](100) NULL,
    [SENDING_SOURCE] [varchar](100) NULL,
	[TO_SENDER] [varchar](100) NULL,
	[DATE_ENVOI] [varchar](20) NULL,
	[SMS_CAMPAIGN_NAME] [varchar](100) NULL,
	[CATEGORY] [varchar](100) NULL

)


  ALTER TABLE ACM_WORKFLOW_STEP
ADD CODE_ACM_TEMPLATE_SMS VARCHAR (100) 
  ALTER TABLE ACM_COLLECTION_STEP
ADD CODE_ACM_TEMPLATE_SMS VARCHAR (100) 

 INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY, ACM_ENABLED,DESCRIPTION)
 VALUES ('SERVICE_SMS',1,'Disable/Enable SMS Service')
