---- ACM-615
------------
INSERT INTO [dbo].[ACM_SETTING_STATUT_WORKFLOW] ([CODE],[LIBELLE],[DESCRIPTION],[CODE_STATUT_LOAN],[STATUT_LOAN],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], IHM_WEB_ROOT, 
	[CLIENT], [BPMN_PROCESS_NAME], [ORDER_ETAPE_PROCESS], [SHOW_IB] ,[CODE_STATUT_IB])
     VALUES (22,'Issued','Issued => Approved'
           ,4,'Approved'
           ,0,GETDATE(),'ADMIN',0,'loan-approval', 'BRJMF','process_loan_BRJMF',20,1,4);
           
--  "0 0 0/6 * * ?" = run job Every 6 hours of every day.
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('CRON_EXPRESSION_DISBURSEMENT_CASE_CLOSURE', '0 0 0/6 * * ?', 1, '2020-10-28', 0);   


--  DEFAULT_ACM_RECEIVER_EMAIL : mail1, mail2, mail3,...
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('DEFAULT_ACM_RECEIVER_EMAIL', 'haythem.benizid@dqlick.com, acm-dev@talys-consulting.com', 1, '2020-11-04', 0);  
