--- RESET DB : ACM_LOAN_PARTICIPANTS 
IF OBJECT_ID('dbo.ACM_LOAN_PARTICIPANTS', 'U') IS NOT NULL
DROP TABLE dbo.ACM_LOAN_PARTICIPANTS;
 
CREATE TABLE ACM_LOAN_PARTICIPANTS(
    ID_ACM_LOAN_PARTICIPANTS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT,
	USERNAME VARCHAR (256),
 	DATE_DEBUT DATETIME NULL,
 	DATE_FIN DATETIME NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);

---------------------
--ACM-733
---------------------
ALTER TABLE ACM_LOAN 
    ADD
    LOAN_CALCULATION_MODE INT NULL,
	APR BIGINT NULL,
	EFFECTIVE_INT_RATE BIGINT NULL;
	
---------------------
--ACM-736
---------------------	
ALTER TABLE ACM_CUSTOMER add PERSON_ID_EXTERN BIGINT  NULL	

	