--- ACM_HABILITATION_IHM_BUTTON

 INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','ISSUANCE_REPAYEMENT','IHM_RUN_INCENTIVE','ISSUANCE_REPAYEMENT',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_RUN_INCENTIVE';

  INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','REGISTRATION','IHM_RUN_INCENTIVE','REGISTRATION',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_RUN_INCENTIVE';

 INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','OPERATION','IHM_RUN_INCENTIVE','OPERATION',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_RUN_INCENTIVE';

  INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','LEGEL','IHM_RUN_INCENTIVE','LEGEL',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_RUN_INCENTIVE';

--- ACM_HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_RUN_INCENTIVE' ,'run-incentive' ,'ISSUANCE_REPAYEMENT'  ,0,GETDATE(),'ADMIN',0, 'RUN INCENTIVE SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_RUN_INCENTIVE' ,'run-incentive' ,'REGISTRATION'  ,0,GETDATE(),'ADMIN',0,'RUN INCENTIVE SCREEN' from ACM_GROUPE

 
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_RUN_INCENTIVE' ,'run-incentive' ,'OPERATION'  ,0,GETDATE(),'ADMIN',0,'RUN INCENTIVE SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_RUN_INCENTIVE' ,'run-incentive' ,'LEGEL'  ,0,GETDATE(),'ADMIN',0,'RUN INCENTIVE SCREEN' from ACM_GROUPE 
 
---Update allowed Role 
update ACM_HABILITATION set ACTIONS = 'EXECUTE' where ID_ACM_HABILITATION in(
select ID_ACM_HABILITATION from ACM_HABILITATION where GROUPE_ID in (
select ID_ACM_GROUPE from ACM_GROUPE where code = 'IT_ADMINISTRATOR') and ACM_HABILITATION = 'IHM_RUN_INCENTIVE' and VALUE = 'ISSUANCE_REPAYEMENT')


update ACM_HABILITATION set ACTIONS = 'EXECUTE' where ID_ACM_HABILITATION in(
select ID_ACM_HABILITATION from ACM_HABILITATION where GROUPE_ID in (
select ID_ACM_GROUPE from ACM_GROUPE where code in ('IT_ADMINISTRATOR','TELLER')) and ACM_HABILITATION = 'IHM_RUN_INCENTIVE' and VALUE = 'REGISTRATION')


update ACM_HABILITATION set ACTIONS = 'EXECUTE' where ID_ACM_HABILITATION in(
select ID_ACM_HABILITATION from ACM_HABILITATION where GROUPE_ID in (
select ID_ACM_GROUPE from ACM_GROUPE where code = 'IT_ADMINISTRATOR') and ACM_HABILITATION = 'IHM_RUN_INCENTIVE' and VALUE = 'OPERATION')


update ACM_HABILITATION set ACTIONS = 'EXECUTE' where ID_ACM_HABILITATION in(
select ID_ACM_HABILITATION from ACM_HABILITATION where GROUPE_ID in (
select ID_ACM_GROUPE from ACM_GROUPE where code in ('IT_ADMINISTRATOR','TELLER')) and ACM_HABILITATION = 'IHM_RUN_INCENTIVE' and VALUE = 'LEGEL')

 