CREATE TABLE [ACM_LOAN_COLLATERAL_TYPE](
[ID] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
[CODE] [varchar](256) NULL,
[DESCRIPTION] [varchar](256) NULL,
[COLLECTION_POURCENTAGE] [int] NULL, 
[COLLECTION_COST] [bigint] NULL, 
[OVERRIDE_COLLECTION_DATA] [bit] NULL,
[DEFAULT_TYPE] [bit] NULL,
[link_TO_ACCOUNT] [bit] NULL,
COLLATERAL_TYPE_DESCRIPTION varchar(256),

[ACM_ENABLED] [bit] NOT NULL,
[DATE_INSERTION] [date] NULL, 
[INSERT_BY] [varchar](256) NULL, 
[DATE_LAST_UPDATE] [date] NULL,
[UPDATED_BY] [varchar](256) NULL,
[ACM_VERSION] [int] NULL
)

CREATE TABLE [ACM_LOAN_COLLATERAL_TYPE_PRODUCT] (
ID_LOAN_COLLATERAL_TYPE BIGINT NOT NULL,
ID_PRODUCT BIGINT NOT NULL,
PRIMARY KEY ([ID_LOAN_COLLATERAL_TYPE],[ID_PRODUCT]),
FOREIGN KEY ([ID_PRODUCT]) REFERENCES ACM_PRODUCT(ID_ACM_PRODUCT),
FOREIGN KEY (ID_LOAN_COLLATERAL_TYPE) REFERENCES ACM_LOAN_COLLATERAL_TYPE([ID]));

 
CREATE TABLE [ACM_COLLATERAL](
	[ID_ACM_COLLATERAL] [bigint] IDENTITY(1,1) NOT NULL,
	[ACM_LOAN_ID] [bigint] NULL,
	[LOAN_ID] [bigint] NULL,
	[REFERENCE] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](200) NOT NULL,
	[COLLATERAL_TYPE_ID_EXTERN] [int] NULL,
	[ID_ACCOUNT_EXTERN] [bigint] NULL,
	[CUSTOMER_ID] [bigint] NULL,
	[ACM_CUSTOMER_ID] [bigint] NULL,
	[ORIGINAL_GROSS_VALUE] [money] NULL,
	[GROSS_VALUE] [money] NOT NULL,
	[REALISED_VALUE] [money] NOT NULL,
	[FIXED_COST] [money] NOT NULL,
	[NET_VALUE] [money] NOT NULL,
	[VALUE_DATE] [smalldatetime] NOT NULL,
	[EXPIRY_DATE] [smalldatetime] NULL,
	[VALUER_ID] [tinyint] NULL,
	[VALUER_NAME] [nvarchar](200) NULL,
	[WITHHOLDING_RATE] [decimal](18, 6) NOT NULL,
	[CU_CREDIT_LINE_ACCOUNT_ID] [bigint] NULL,
	[IS_DELETED] [bit] NOT NULL,
	[COLLATERAL_TYPE_DESCRIPTION] [varchar](256) NULL,

	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [date] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL

	FOREIGN KEY ([ACM_CUSTOMER_ID] )REFERENCES [ACM_CUSTOMER] ([ID_ACM_CUSTOMER]),
	FOREIGN KEY ([ACM_LOAN_ID]) REFERENCES  [ACM_LOAN] ([ID_ACM_LOAN])
	
) 
 
