IF OBJECT_ID('dbo.ACM_3RD_PARTY_HISTORIQUE', 'U') IS NOT NULL
DROP TABLE dbo.ACM_3RD_PARTY_HISTORIQUE;

CREATE TABLE ACM_3RD_PARTY_HISTORIQUE(
    ID_ACM_3RD_PARTY_HISTORIQUE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_LOAN BIGINT NULL,
    ID_CUSTOMER BIGINT NULL,
    ID_CUSTOMER_GUARANTOR BIGINT NULL,
    IDENTITY_CUSTOMER VARCHAR (256) NULL,
    IDENTITY_CUSTOMER_GUARANTOR VARCHAR (256) NULL,
    CATEGORY VARCHAR (256) NULL, -- AML - I-SCORE - KYC
    REPONSE_STATUS VARCHAR (50) NULL,
    REQUEST_VALUE VARCHAR(MAX) NULL,
    REPONSE_VALUE VARCHAR(MAX) NULL,
    
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);

ALTER TABLE ACM_3RD_PARTY_HISTORIQUE ALTER COLUMN REQUEST_VALUE VARCHAR(MAX) COLLATE Arabic_CI_AI_KS_WS;
ALTER TABLE ACM_3RD_PARTY_HISTORIQUE ALTER COLUMN REPONSE_VALUE VARCHAR(MAX) COLLATE Arabic_CI_AI_KS_WS;
