INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_SOAP_REQUEST_USER', 'mf0018000100013ab', 1, '2021-03-10', 0, 'FUNCTIONAL');
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_SOAP_REQUEST_PASS', 'Tamkeen1234', 1, '2021-03-10', 0, 'FUNCTIONAL');
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_SOAP_REQUEST_PATH', '#', 1, '2021-03-10', 0, 'FUNCTIONAL');