ALTER TABLE acm_loan
ADD OPENING_BALANCE decimal(16,4);

ALTER TABLE acm_loan
 ADD LOAN_APPLICATION_STATUS varchar(100);

 ALTER TABLE acm_loan
 ADD CONSTRAINT df_status
DEFAULT 'NEW_APPLICATION' FOR LOAN_APPLICATION_STATUS;

ALTER TABLE ACM_PRODUCT
 ADD TOPUP bit; 
 
 ALTER TABLE ACM_PRODUCT
 ADD REFINANCE bit;  

update ACM_LOAN set LOAN_APPLICATION_STATUS = 'NEW_APPLICATION' where LOAN_APPLICATION_STATUS is null

-- [ACM_HABILITATION]

	INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
	select 'READ','ACM' ,id_acm_groupe ,'IHM_TOPUP_REFINANCE_LOAN' ,'topup-refinance-loan' ,'TOPUP_REFINANCE'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE

--[ACM_HABILITATION_IHM_ROUTE]
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
		VALUES('ACM','IHM_TOPUP_REFINANCE_LOAN','topup-refinance-loan' ,'page topup or refinance Loan' ,1,GETDATE(),'ADMIN',0);


--[ACM_HABILITATION_IHM_BUTTON]

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','TOPUP_REFINANCE','IHM_TOPUP_REFINANCE_LOAN','TOPUP_REFINANCE',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_TOPUP_REFINANCE_LOAN';