update ACM_USERS set ACCESS_BRANCHES='Jeddah,Madinah,Tabuk' where USERNAME='Khezimame'

update ACM_USERS set ACCESS_BRANCHES='Riyadh,Dammam' where USERNAME='Metwallyaa'

update ACM_USERS set ACCESS_BRANCHES='Jeddah,Madinah,Tabuk,Riyadh,Dammam' where USERNAME='Sammanhy'

-------------
﻿----- TABLE : [ACM_SETTING_MOTIFS_REJET]

GO
SET IDENTITY_INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ON 
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10013, N'SUBJECT_IB', N'INCIDENT', N'Incident / بلاغ', N'قبل اتخاذ اجراء قانوني ضد العميل', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10014, N'SUBJECT_IB', N'ENQUERY', N'Enquery / استعلام', N'عام - لمنتج اوخدمة', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10015, N'SUBJECT_IB', N'SUGGESTION', N'Suggestion / اقتراح', N'ممكن ان يزودنا العميل باقتراح لتحسين المنتج او اخذ تمويل إضافي', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10016, N'SUBJECT_IB', N'LOAN_RENEW_REQUEST', N'Loan renew Request (for working loans) / تجديد قرض', N'للعملاء الجيدين', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10017, N'SUBJECT_IB', N'EVALUATION', N'Evaluation / تقييم الخدمة', N'بعد التمويل', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10018, N'SUBJECT_IB', N'MEETING_REQUEST', N'Meeting request / حجز اجتماع', N'اجتماع اللجنة', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10019, N'SUBJECT_IB', N'COMPLAINT', N'Complaint / شكوى', N'ارسال رسائل بقنوات الشكاوى المتاحة للعملاء', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10020, N'SUBJECT_IB', N'OTHER', N'Other / طلب آخر', N'طلب آخر', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] ([ID_ACM_SETTING_MOTIFS_REJET], [CATEGORIE], [CODE], [LIBELLE], [DESCRIPTION], [ACM_ENABLED], [DATE_INSERTION], [INSERT_BY], [DATE_LAST_UPDATE], [UPDATED_BY], [ACM_VERSION], [CODE_EXTERNAL]) VALUES (10021, N'SUBJECT_IB', N'CANCEL_APPlICATION', N'Cancel application / إلغاء التطبيق', N'إلغاء التطبيق', 1, CAST(N'2020-10-07' AS Date), N'ADMIN', NULL, NULL, 0, NULL)
SET IDENTITY_INSERT [dbo].[ACM_SETTING_MOTIFS_REJET] OFF

 