--ACM-618
----- TABLE : ACM_LINKS_RELATIONSHIPS
ALTER TABLE ACM_LINKS_RELATIONSHIPS
ADD ID_ACM_LOAN bigint,
AMOUNT_GUARANTOR bigint;

--- ACM-473
----- TABLE : ACM_PRODUCT
ALTER TABLE ACM_PRODUCT ADD MAXIMUM_BALANCE BIGINT NULL;
ALTER TABLE ACM_PRODUCT ADD MINIMUM_TERM INT NULL;
ALTER TABLE ACM_PRODUCT ADD MAXIMUM_TERM INT NULL;

ALTER TABLE ACM_PRODUCT ADD ISSUE_FEE_PERCENTAGE_1 BIGINT NULL;
ALTER TABLE ACM_PRODUCT ADD ISSUE_FEE_PERCENTAGE_2 BIGINT NULL;
ALTER TABLE ACM_PRODUCT ADD ISSUE_FEE_PERCENTAGE_3 BIGINT NULL;
ALTER TABLE ACM_PRODUCT ADD ISSUE_FEE_PERCENTAGE_4 BIGINT NULL;

ALTER TABLE ACM_PRODUCT ADD USE_SCHEDULE_INTEREST BIT NULL;
ALTER TABLE ACM_PRODUCT ADD CAPITALISE_INTEREST_WHEN_REFINANCING BIT NULL;

----------
ALTER TABLE IB_LOAN ADD ID_LOAN_EXTERN BIGINT NULL;

alter table [ACM_CUSTOMER_CONTACT] ALTER COLUMN [SUBJECT] VARCHAR (512) COLLATE Arabic_CI_AI_KS_WS;
alter table [ACM_CUSTOMER_CONTACT] ALTER COLUMN [CONTENT] VARCHAR (512) COLLATE Arabic_CI_AI_KS_WS; 

---

alter table ACM_LOAN_APPROVAL_HISTORIQUE ALTER COLUMN APPROVAL_NOTE  VARCHAR (512) COLLATE Arabic_CI_AI_KS_WS; 