ALTER TABLE ACM_CONDITIONNAL_APPROVE 
 add   CONDITIONNAL_VALIDATION  bit;

 ALTER TABLE ACM_CONDITIONNAL_APPROVE
 ADD USERNAME_INSERTED_BY varchar(256);

 alter table  ACM_CONDITIONNAL_APPROVE 
add  APPROVAL_CONDITION_DATE dateTime

alter table ACM_CONDITIONNAL_APPROVE
add  ID_ACM_CALENDAR_EVENT_VALIDATOR bigint