-- rename LOAN_INSTANCE.CODE TO INSTANCE.ID_ACM_WORKFLOW_STEP
EXEC sp_rename 'ACM_LOAN_INSTANCE.CODE', 'ID_ACM_WORKFLOW_STEP';

-- rename ACM_LOAN.ETAPE_WORKFLOW to  ID_ACM_WORKFLOW_STEP to 
EXEC sp_rename 'ACM_LOAN.ETAPE_WORKFLOW', 'ID_ACM_WORKFLOW_STEP';

-- drop old tables
drop table IF EXISTS ACM_COLL_PARTICIPANTS_ASSOC
drop table IF EXISTS ACM_COLL_DOC_PRODUCT_ASSOC
drop table IF EXISTS ACM_COLL_GROUP_ASSOC
drop table IF EXISTS ACM_COLL_INSTANCE_THIRD_PARTY_ASSOC
drop table IF EXISTS ACM_COLL_PARTICIPANTS_ASSOC
drop table IF EXISTS ACM_LOAN_INSTANCE_GROUPE_ASSOCIATION
drop table IF EXISTS ACM_LOAN_PARTICIPANTS_APPROVAL_ASSOC
drop table IF EXISTS ACM_LOAN_PARTICIPANTS_ASSOC
drop table IF EXISTS ACM_WORKFLOW_DOC_PRODUCT_ASSOC
drop table IF EXISTS ACM_ASSET_LOAN_ASS
drop table if EXISTS ACM_COLLECTION_INSTANCE_ACM_THIRD_PARTY;
drop table IF EXISTS ACM_ASSET_ACM_LOAN;
drop table IF EXISTS ACM_COLLECTION_INSTANCE
drop table IF EXISTS ACM_ASSET
drop table IF EXISTS ACM_SUPPLIER
drop table IF EXISTS ACM_WORKFLOW_STEP_ACM_GROUPE_PARTICIPANT
drop table IF EXISTS ACM_COLLECTION_STEP_ACM_DOCUMENT_TYPE_PRODUCT
drop table IF Exists ACM_WORKFLOW_STEP_ACM_GROUPE_APPROVAL
drop table IF Exists ACM_LOAN_INSTANCE_ACM_GROUPE_APPROVAL
drop table if exists ACM_WORKFLOW_STEP_ACM_DOCUMENT_TYPE_PRODUCT
drop table if exists ACM_COLL_THIRD_PARTY_ASSOC
drop table if exists ACM_COLLECTION_THIRD_PARTY

 CREATE TABLE ACM_COLLECTION_STEP_ACM_DOCUMENT_TYPE_PRODUCT(
    [ACM_COLLECTION_STEP_ID] [bigint] NOT NULL,
    [ACM_DOCU_TYPE_PROD_ID] [bigint] NOT NULL,
CONSTRAINT FK_C FOREIGN KEY (ACM_COLLECTION_STEP_ID) REFERENCES ACM_COLLECTION_STEP(ID_ACM_COLLECTION_STEP),
CONSTRAINT FK_D FOREIGN KEY (ACM_DOCU_TYPE_PROD_ID) REFERENCES ACM_SETTING_DOC_PRODUCT(ID_ACM_SETTING_DOC_PRODUCT),
CONSTRAINT PK PRIMARY KEY (ACM_COLLECTION_STEP_ID,ACM_DOCU_TYPE_PROD_ID)
)


--ACM-2276 

----- TABLE ASSOCIATION : ACM_WORKFLOW_STEP_ACM_GROUPE_PARTICIPANT
   CREATE TABLE ACM_WORKFLOW_STEP_ACM_GROUPE_PARTICIPANT (
    ACM_LOAN_STEP_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
    PRIMARY KEY (ACM_LOAN_STEP_ID,ACM_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE),
); 


----- TABLE ASSOCIATION : ACM_WORKFLOW_STEP_ACM_GROUPE_APPROVAL
   CREATE TABLE ACM_WORKFLOW_STEP_ACM_GROUPE_APPROVAL (
    ACM_LOAN_STEP_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
    PRIMARY KEY (ACM_LOAN_STEP_ID,ACM_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE)
); 



----- TABLE ASSOCIATION : ACM_LOAN_INSTANCE_ACM_GROUPE_APPROVAL
   CREATE TABLE ACM_LOAN_INSTANCE_ACM_GROUPE_APPROVAL (
    LOAN_INSTANCE_GROUPE_ID  BIGINT NOT NULL IDENTITY(1,1),
    ACM_LOAN_INSTANCE_ID BIGINT NOT NULL,
    ACM_GROUPE_ID BIGINT NOT NULL,
	ACM_OWNER VARCHAR (512) NULL,
	ACM_OWNER_NAME VARCHAR (1000) NULL,
	ACM_GROUPE_NAME VARCHAR (256) NULL,
	ACM_GROUPE_CODE VARCHAR (256) NULL,
	ACM_LOAN_VALIDATION BIT NULL,

    ACM_ENABLED BIT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,

    PRIMARY KEY (ACM_LOAN_INSTANCE_ID,ACM_GROUPE_ID,LOAN_INSTANCE_GROUPE_ID),
    FOREIGN KEY (ACM_LOAN_INSTANCE_ID) REFERENCES ACM_LOAN_INSTANCE (ID_ACM_LOAN_INSTANCE),
    FOREIGN KEY (ACM_GROUPE_ID) REFERENCES ACM_GROUPE(ID_ACM_GROUPE),
); 
-- ACM-2257
CREATE TABLE [ACM_SUPPLIER](
	[ID_ACM_SUPPLIER] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[TYPE_ID] [bigint] NULL,
	[NAME] [varchar](100) NULL,
	[ACTIVITY] [bigint] NULL,
	[ACRONYME] [varchar](100) NULL,
	[LEGAL_CATALOG] [bigint] NULL,
	[COMMERCIAL_NAME] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[ACTIVITY_START_DATE] [date] NULL,
	[PATENT_NUMBER] [varchar](100) NULL,
	[TELEPHONE] [varchar](100) NULL,
	[FAX] [varchar](100) NULL,
	[WEB_SITE] [varchar](100) NULL,
	[STATUS] [bigint] NULL,
	[PERIODICITY] [bigint] NULL,
	[ACM_ENABLED] [bit] NULL,
	[DATE_INSERTION] [date] NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[ACM_VERSION] [int] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[INSERT_BY] [varchar](256) NULL,
	[OBJECTIF] [varchar](100) NULL)

--ACM-2257
CREATE TABLE ACM_ASSET(
ID_ACM_ASSET  BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SUPPLIER_ID BIGINT,
SUPPLIER_NAME  VARCHAR (256),
CODE_ARTICLE VARCHAR (256),
DATE_DEBUT DATE,
DATE_FIN  DATE,
LIBELLE VARCHAR (256),
DESCRIPTION VARCHAR (256),
PRIX_UNITAIRE decimal(16,4),
REMISE_ARTICLE decimal(16,4),
    ACM_ENABLED BIT NOT NULL,
    DATE_INSERTION DATETIME NULL,
    INSERT_BY  VARCHAR (256) NULL,
    DATE_LAST_UPDATE DATETIME NULL,
    UPDATED_BY  VARCHAR (256) NULL,
    ACM_VERSION INT NULL ,	
    FOREIGN KEY (SUPPLIER_ID) REFERENCES ACM_SUPPLIER([ID_ACM_SUPPLIER])
    )
-- ACM-2259
CREATE TABLE ACM_ASSET_ACM_LOAN(
	ID_ACM_ASSET_ACM_LOAN bigint IDENTITY(1,1) NOT NULL,
	ID_ACM_LOAN bigint NULL,
	ID_ACM_ASSET bigint NULL,

	PRIX_UNITAIRE decimal(16, 4) NULL,
	REMISE_ARTICLE decimal(16, 4) NULL,
	QUANTITE_ARTICLE int NOT NULL default 1,

	ACM_ENABLED bit NOT NULL,
	DATE_INSERTION datetime NULL,
	INSERT_BY varchar(256) NULL,
	DATE_LAST_UPDATE datetime NULL,
	UPDATED_BY varchar(256) NULL,
	ACM_VERSION int NULL,

	PRIMARY KEY (ID_ACM_ASSET_ACM_LOAN)
);

ALTER TABLE ACM_ASSET_ACM_LOAN  WITH CHECK ADD FOREIGN KEY(ID_ACM_ASSET)
REFERENCES ACM_ASSET (ID_ACM_ASSET);

ALTER TABLE ACM_ASSET_ACM_LOAN  WITH CHECK ADD FOREIGN KEY(ID_ACM_LOAN)
REFERENCES ACM_LOAN (ID_ACM_LOAN);



--ACM-2261
----- TABLE ASSOCIATION : ACM_WORKFLOW_STEP_ACM_DOCUMENT_TYPE_PRODUCT 

 CREATE TABLE ACM_WORKFLOW_STEP_ACM_DOCUMENT_TYPE_PRODUCT  (
 ACM_WORKFLOW_STEP_ID BIGINT NOT NULL,
 ACM_DOCU_TYPE_PROD_ID BIGINT NOT NULL

 PRIMARY KEY (ACM_WORKFLOW_STEP_ID,ACM_DOCU_TYPE_PROD_ID)

 FOREIGN KEY (ACM_WORKFLOW_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
 FOREIGN KEY (ACM_DOCU_TYPE_PROD_ID) REFERENCES ACM_SETTING_DOC_PRODUCT(ID_ACM_SETTING_DOC_PRODUCT),
);

-- ACM-2226
 
CREATE TABLE ACM_COLLECTION_THIRD_PARTY(   
    ID_ACM_THIRD_PARTY_LEGAL_COLLECTION BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR (256) NULL,
    LAST_NAME VARCHAR (256) NULL,
    ADDRESS_PARTY VARCHAR (512) NULL,
    EMAIL VARCHAR (512) NULL,
    PHONE_NUMBER VARCHAR (512) NULL,
    ACCESS_BRANCHES VARCHAR (512) NULL,
    TYPE_PARTY VARCHAR (512) NULL,
    BRANCHID int,
    BRANCHE_NAME varchar(512),
    BRANCHE_DESCRIPTION varchar(512),
    ACM_ENABLED BIT NOT NULL,
    DATE_INSERTION DATETIME NULL,
    INSERT_BY  VARCHAR (256) NULL,
    DATE_LAST_UPDATE DATETIME NULL,
    UPDATED_BY  VARCHAR (256) NULL,
    ACM_VERSION INT NULL
    );


----- TABLE ASSOCIATION : ACM_COLL_THIRD_PARTY_ASSOC
 

	CREATE TABLE ACM_COLL_THIRD_PARTY_ASSOC (
	ACM_COLLECTION_ID BIGINT NOT NULL,
	ACM_THIRD_PARTY_ID BIGINT NOT NULL
	PRIMARY KEY (ACM_COLLECTION_ID,ACM_THIRD_PARTY_ID)
	FOREIGN KEY (ACM_COLLECTION_ID) REFERENCES ACM_COLLECTION(ID_ACM_COLLECTION),
	FOREIGN KEY (ACM_THIRD_PARTY_ID) REFERENCES ACM_COLLECTION_THIRD_PARTY(ID_ACM_THIRD_PARTY_LEGAL_COLLECTION),
); 

 

-- TABLE COLLECTION INSTANCE
 CREATE TABLE ACM_COLLECTION_INSTANCE(
	ID_ACM_COLLECTION_INSTANCE BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_ACM_COLLECTION BIGINT NOT NULL,
	ID_ACM_COLLECTION_STEP INT NOT NULL,
	LIBELLE VARCHAR(512) NULL,
	DESCRIPTION VARCHAR(512) NULL,
	CODE_STATUT_COLLECTION BIGINT NULL,
	STATUT_COLLECTION VARCHAR(512) NULL,
	IHM_WEB_ROOT VARCHAR(512) NULL,
	CLIENT VARCHAR(256) NULL,
	ORDER_ETAPE_PROCESS INT NULL,
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY VARCHAR(256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY VARCHAR(256) NULL,
	ACM_VERSION INT NULL,
	START_DATE INT NULL,
	AFTER_DATE VARCHAR(256) NULL,
	STEP_NAME VARCHAR(256) NULL,
	ACTION_USER VARCHAR(50) NULL);

 

----- TABLE ASSOCIATION : ACM_COLLECTION_INSTANCE_ACM_THIRD_PARTY
 

   CREATE TABLE ACM_COLLECTION_INSTANCE_ACM_THIRD_PARTY (
    ACM_COLLECTION_INSTANCE_ID BIGINT NOT NULL,
    ACM_THIRD_PARTY_ID BIGINT NOT NULL
    PRIMARY KEY (ACM_COLLECTION_INSTANCE_ID,ACM_THIRD_PARTY_ID)
    FOREIGN KEY (ACM_COLLECTION_INSTANCE_ID) REFERENCES ACM_COLLECTION_INSTANCE(ID_ACM_COLLECTION_INSTANCE),
    FOREIGN KEY (ACM_THIRD_PARTY_ID) REFERENCES ACM_COLLECTION_THIRD_PARTY(ID_ACM_THIRD_PARTY_LEGAL_COLLECTION),
); 

-- ADD HABILITATION SETTING_THIRD_PARTY
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_SETTING_THIRD_PARTY' ,'setting-collection-third-party' ,'IHM',1,GETDATE(),'ADMIN',0 from ACM_GROUPE


--ADD ROUTE HABILITATION SETTING_THIRD_PARTY
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES('ACM','IHM_SETTING_THIRD_PARTY','setting-collection-third-party' ,'page setting legal collection third party' ,1,GETDATE(),'ADMIN',0);

 -- cron schedule every night at midnight
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('CRON_EXPRESSION_COLLECTION', '0 0/0 0 * * *', 1, '2022-10-27', 0);
