INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_API_REQUEST_TYPE', 'JSONANDPDF', 1, '2022-01-28', 0, 'FUNCTIONAL');

INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_API_REQUEST_LANG', 'EN', 1, '2022-01-28', 0, 'FUNCTIONAL');

INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('TAMKEEN_API_REQUEST_LOAN_TYPE', '001', 1, '2022-01-28', 0, 'FUNCTIONAL');