INSERT INTO [dbo].[ACM_SETTING_NOTIFICATION]([CATEGORY],[TYPE_NOTIF],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[DATE_LAST_UPDATE],[UPDATED_BY],[ACM_VERSION]) 
VALUES ('LOAN','SYNCHRO-CALENDAR',1,'2023-15-05 18:09:02.843','ADMIN',null,null,0 ) ;
INSERT INTO [dbo].[ACM_SETTING_NOTIFICATION]([CATEGORY],[TYPE_NOTIF],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[DATE_LAST_UPDATE],[UPDATED_BY],[ACM_VERSION]) 
VALUES ('COLLECTION','SYNCHRO-CALENDAR',1,'2023-15-05 18:09:02.843','ADMIN',null,null,0 ) ;
INSERT INTO [dbo].[ACM_SETTING_NOTIFICATION]([CATEGORY],[TYPE_NOTIF],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[DATE_LAST_UPDATE],[UPDATED_BY],[ACM_VERSION]) 
VALUES ('LEGAL','SYNCHRO-CALENDAR',1,'2023-15-05 18:09:02.843','ADMIN',null,null,0 ) ;
INSERT INTO [dbo].[ACM_SETTING_NOTIFICATION]([CATEGORY],[TYPE_NOTIF],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[DATE_LAST_UPDATE],[UPDATED_BY],[ACM_VERSION]) 
VALUES ('PROSPECT','SYNCHRO-CALENDAR',1,'2023-15-05 18:09:02.843','ADMIN',null,null,0 ) 
ALTER TABLE dbo.[ACM_SETTING_NOTIFICATION] 
ADD TYPE VARCHAR(20) NULL ;
update [ACM_SETTING_NOTIFICATION] set type  = 'GLOBAL' where CATEGORY in ('REMINDER','WORKFLOW');
update [ACM_SETTING_NOTIFICATION] set type  = 'CALENDAR' where TYPE_NOTIF ='SYNCHRO-CALENDAR';