INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [racine_id])		    
		VALUES('ACM','IHM_EDIT_COLLECTION_THIRD_PARTY','setting-collection-third-party' ,'page EDIT COLLECTION THIRD PARTY' ,1,GETDATE(),'ADMIN',0,2);

INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [racine_id])		    
		VALUES('ACM','IHM_ADD_COLLECTION_THIRD_PARTY','add-setting-collection-third-party' ,'page ADD COLLECTION THIRD PARTY' ,1,GETDATE(),'ADMIN',0,2);

-- ACM_HABILITATION
-----------------------------
-- 
----------------------------
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_EDIT_COLLECTION_THIRD_PARTY' ,'setting-collection-third-party' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'Edit setting third party' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_EDIT_COLLECTION_THIRD_PARTY' ,'setting-collection-third-party' ,'UPDATE'  ,0,GETDATE(),'ADMIN',0, 'Edit setting third party' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION], [DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_ADD_COLLECTION_THIRD_PARTY' ,'add-setting-collection-third-party' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'ADD setting third party' from ACM_GROUPE


UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE
where CODE_IHM_ROUTE = 'IHM_EDIT_COLLECTION_THIRD_PARTY'

UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE
where CODE_IHM_ROUTE = 'IHM_ADD_COLLECTION_THIRD_PARTY'
