--  "0 0/30 * * * ?" = run job Every 30 mins of every day.
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('CRON_EXPRESSION_PRODUCTS', '0 0/30 * * * ?', 1, '2020-07-30', 0);
