-- PRODUCT_ID_ABACUS, PRODUCT_TYPE_ID_ABACUS, CREATION_DATE_ABACUS, EDIT_DATE_ABACUS
alter table ACM_PRODUCT add PRODUCT_ID_ABACUS BIGINT NULL;
alter table ACM_PRODUCT add PRODUCT_TYPE_ID_ABACUS BIGINT NULL;
alter table ACM_PRODUCT add CREATION_DATE_ABACUS DATETIME NULL;
alter table ACM_PRODUCT add EDIT_DATE_ABACUS DATETIME NULL;

