

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_MEZA_CARD', 'U') IS NOT NULL
DROP TABLE dbo.ACM_MEZA_CARD;

-------------
----- TABLE : ACM_MEZA_CARDS
-- ACM : DATA BASE
CREATE TABLE ACM_MEZA_CARD (
    ID_ACM_MEZA_CARD BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MERCHANT_ID BIGINT,
	CARD_TYPE VARCHAR(50),
	CARD_NUMBER VARCHAR(50),
	ACCOUNT VARCHAR(50),
	EXPIRTY_DATE DATE,
	ACTIVITY_DATE DATE,
	EMBOSSED_NAME VARCHAR(50),
	STATUS VARCHAR(50),
	BRANCH_ID BIGINT,
	BRANCH_NAME VARCHAR(50),
	ACM_ID_CUSTOMER BIGINT,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	FOREIGN KEY (ACM_ID_CUSTOMER) REFERENCES ACM_CUSTOMER (ID_ACM_CUSTOMER)
)

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_MEZA_CARD_SETTING' ,'setting-meza-card' ,'IHM'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_MEZA_CARD_ACTIVATE' ,'activate-meza-card' ,'IHM'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE