   /** add ASSIGN_CUSTOMER setting*/ 
  INSERT INTO [DBO].[ACM_ENVIRONNEMENT] ([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('ASSIGN_CUSTOMER', 0, 0, '2021-02-17', 0);