   /** add talys copyrights footer*/ 
	INSERT INTO [ACM_ENVIRONNEMENT]
  ([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION]) 
VALUES ('TALYS_COPYRIGHTS', '© 2021 TALYS, All Rights Reserved', 1, '2021-02-12', 0);