-- (ABACUS) cuLoanCollateral <--> COLLATERAL (ACM)
-- (ABACUS) cuLoanGuarantor <--> Saisie Garants - GUARANTOR (ACM)

INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (1 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (2 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (4 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (6 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (7 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (20 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (21 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (22 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (25 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
     
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (24 ,'COLLATERAL' ,'cuLoanCollateral' ,'Saisie Garantie' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (24 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (27 ,'COLLATERAL' ,'cuLoanCollateral' ,'Saisie Garantie' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_GUARANTOR_COLLATERAL]([ID_PRODUCT],[CODE],[key_ABACUS] ,[DESCRIPTION], MANDATORY, DATE_DEBUT ,ACM_ENABLED ,[DATE_INSERTION] ,[INSERT_BY] ,[ACM_VERSION])
     VALUES (27 ,'GUARANTOR' ,'cuLoanGuarantor' ,'Saisie Garants' ,1,GETDATE(),1,GETDATE(),'ADMIN',0);
