ALTER TABLE ACM_LOAN 
    ADD 
        CREATION_DATE_ABACUS DATETIME NULL,
        APPLY_AMOUNT_TOTAL BIGINT NULL,
        ISSUE_FEE_AMOUNT BIGINT NULL,
        TERM_PERIOD INT NULL,
        PERIOD_FREQ VARCHAR (256) NULL,
        ISSUE_DATE DATETIME NULL,
        PRODUCT_RATE INT  NULL,
        GRACE_PERIOD INT NULL,
        ACCOUNT_INDUSTRY_CODE_CODE VARCHAR (256) NULL,
        ACCOUNT_INDUSTRY_CODE_DESCRIPTION VARCHAR (256) NULL,
        PRODUCT_LOAN_REASONS_CODE VARCHAR (256) NULL,
 		PRODUCT_LOAN_REASONS_DESCRIPTION VARCHAR (256) NULL;
 
ALTER TABLE [ACM].[dbo].[ACM_LOAN]
	ALTER COLUMN [ACCOUNT_INDUSTRY_CODE_CODE] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;
ALTER TABLE [ACM].[dbo].[ACM_LOAN]
	ALTER COLUMN [ACCOUNT_INDUSTRY_CODE_DESCRIPTION] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;
ALTER TABLE [ACM].[dbo].[ACM_LOAN]
	ALTER COLUMN [PRODUCT_LOAN_REASONS_CODE] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;
ALTER TABLE [ACM].[dbo].[ACM_LOAN]
	ALTER COLUMN [PRODUCT_LOAN_REASONS_DESCRIPTION] VARCHAR (256) COLLATE Arabic_CI_AI_KS_WS;		
        
        