INSERT INTO [dbo].[ACM_SETTING_LEVEL] ([CODE],[TITLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES ('APPROVAL_L1' ,'Approval L1' ,'Approval L1' ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL] ([CODE],[TITLE],[DESCRIPTION],ACM_ENABLED,[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES ('APPROVAL_L2' ,'Approval L2' ,'Approval L2' ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL] ([CODE],[TITLE],[DESCRIPTION],ACM_ENABLED,[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES ('APPROVAL_L3' ,'Approval L3' ,'Approval L3' ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_LEVEL] ([CODE],[TITLE],[DESCRIPTION],ACM_ENABLED,[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES ('APPROVAL_L4' ,'Approval L4' ,'Approval L4' ,1,GETDATE(),'ADMIN',0);
