IF OBJECT_ID('dbo.ACM_SETTING_GUARANTOR_COLLATERAL', 'U') IS NOT NULL
DROP TABLE dbo.ACM_SETTING_GUARANTOR_COLLATERAL;

CREATE TABLE ACM_SETTING_GUARANTOR_COLLATERAL(

    ID_ACM_SETTING_GUARANTOR_COLLATERAL BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_PRODUCT BIGINT NOT NULL,
	CODE VARCHAR (256) NOT NULL,
	key_ABACUS VARCHAR (256) NOT NULL,
	DESCRIPTION VARCHAR (512) NULL,
	MANDATORY bit NOT NULL,
	DATE_DEBUT date NULL,
	DATE_FIN date NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);