alter table ACM_WORKFLOW_STEP
add APPROVAL_CONDITIONS bit ;


CREATE TABLE [dbo].[ACM_CONDITIONNAL_APPROVE](
	[ID_ACM_CONDITIONNAL_APPROVE] [bigint] IDENTITY(1,1) PRIMARY KEY,
	[DESCRIPTION] [varchar](256) NULL,
	[ACM_ID_LOAN] [bigint] NULL,
	[USERNAME] [varchar](256) NULL,
	[STATUS] [varchar](256) NULL,
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [date] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL,
	FOREIGN KEY([ACM_ID_LOAN])
	REFERENCES [dbo].[ACM_LOAN] ([ID_ACM_LOAN]),
	FOREIGN KEY([USERNAME])
	REFERENCES [dbo].[ACM_USERS] ([USERNAME])

	


	);


