CREATE TABLE ACM_ASSET(
ID_ACM_ASSET  BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SUPPLIER_ID BIGINT,
SUPPLIER_NAME  VARCHAR (256),
CODE_ARTICLE VARCHAR (256),
DATE_DEBUT DATE,
DATE_FIN  DATE,
LIBELLE VARCHAR (256),
DESCRIPTION VARCHAR (256),
PRIX_UNITAIRE decimal(16,4),
REMISE_ARTICLE decimal(16,4),
    ACM_ENABLED BIT NOT NULL,
    DATE_INSERTION DATETIME NULL,
    INSERT_BY  VARCHAR (256) NULL,
    DATE_LAST_UPDATE DATETIME NULL,
    UPDATED_BY  VARCHAR (256) NULL,
    ACM_VERSION INT NULL ,	
    FOREIGN KEY (SUPPLIER_ID) REFERENCES [ACM_SUPPLIER]([ID_ACM_SUPPLIER])
    )
 
