CREATE TABLE ACM_ASSET_ACM_LOAN(
	ID_ACM_ASSET_ACM_LOAN bigint IDENTITY(1,1) NOT NULL,
	ID_ACM_LOAN bigint NULL,
	ID_ACM_ASSET bigint NULL,

	PRIX_UNITAIRE decimal(16, 4) NULL,
	REMISE_ARTICLE decimal(16, 4) NULL,
	QUANTITE_ARTICLE int NOT NULL default 1,

	ACM_ENABLED bit NOT NULL,
	DATE_INSERTION datetime NULL,
	INSERT_BY varchar(256) NULL,
	DATE_LAST_UPDATE datetime NULL,
	UPDATED_BY varchar(256) NULL,
	ACM_VERSION int NULL,

	PRIMARY KEY (ID_ACM_ASSET_ACM_LOAN)
);

ALTER TABLE ACM_ASSET_ACM_LOAN  WITH CHECK ADD FOREIGN KEY(ID_ACM_ASSET)
REFERENCES ACM_ASSET (ID_ACM_ASSET);

ALTER TABLE ACM_ASSET_ACM_LOAN  WITH CHECK ADD FOREIGN KEY(ID_ACM_LOAN)
REFERENCES ACM_LOAN (ID_ACM_LOAN);
