CREATE TABLE ACM_RENEWAL_CONDITION(
    ID_ACM_RENEWAL_CONDITION BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	YEAR INT NOT NULL,
	MIN_AMOUNT BIGINT NOT NULL,
	MAX_AMOUNT BIGINT NOT NULL,
	POURCENTAGE INT NULL,
	ORDRE BIGINT NOT NULL,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
