-- ADD HABILITATION CLAIMS
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )   
             VALUES('ACM','IHM_CLAIMS','claims' ,'page claims list' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));
 
-- ADD HABILITATION CLAIMS
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CLAIMS' ,'claims' ,'IHM'  ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CLAIMS') from ACM_GROUPE ;


-- ADD HABILITATION CLAIMS DETAILS
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )   
             VALUES('ACM','IHM_CLAIMS_DETAILS','claim-detail' ,'page claims details' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));
 
-- ADD HABILITATION CLAIMS DETAILS
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CLAIMS_DETAILS' ,'claim-detail' ,'IHM'  ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CLAIMS_DETAILS') from ACM_GROUPE ;
