-------------
----- TABLE : ACM_CALENDAR_EVENT
create table dbo.ACM_CALENDAR_EVENT (
    ID_ACM_CALENDAR_EVENT BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DATE_DEBUT DATE NOT NULL,
	DATE_FIN DATE NOT NULL,
	TYPE_EVENT  VARCHAR (256) NOT NULL,
	LIBELLE_EVENT VARCHAR (256) NOT NULL,
	DESCRIPTION VARCHAR(5000) NOT NULL,
	USERNAME VARCHAR (256) NOT NULL,
	CUSTOMER_NAME VARCHAR (256) NULL,
	PHONE_NUMBER INT NULL,
	PLACE VARCHAR (256) NULL,
	STATUT VARCHAR (256) NOT NULL,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);