IF OBJECT_ID('dbo.ACM_CUSTOMER_DESICION', 'U') IS NOT NULL
DROP TABLE dbo.ACM_CUSTOMER_DESICION;


CREATE TABLE ACM_CUSTOMER_DESICION(

    ID_ACM_CUSTOMER_DESICION BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT NOT NULL,
	CONTACT_DATE DATE NOT NULL,
	CONTACT_METHOD  VARCHAR (256) NOT NULL,
	COMMENTS  NVARCHAR (MAX) NULL,
    
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL

	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN)
);