 -- CONFIG POURCENTAGE AML
INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION], [CATEGORY]) 
VALUES ('CHACK_AML_MIN_POURCENTAGE', '0', 1, '2021-09-30', 0, 'FUNCTIONAL');


-- ALTER TABLE ACM_3RD_PARTY_HISTORIQUE
ALTER TABLE ACM_3RD_PARTY_HISTORIQUE
ADD AML_CHECK_POURCENTAGE INT NULL;

-- MONEY_LAUNDRY
INSERT INTO [ACM_GROUPE] ([CODE],[LIBELLE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES('MONEY_LAUNDRY','MONEY LAUNDRY GROUP','Groupe For MONEY_LAUNDRY User',1,GETDATE(),'ADMIN',0);


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select [ACTIONS],[CLIENT],(select ID_ACM_GROUPE from ACM_GROUPE where code = 'MONEY_LAUNDRY'),
[ACM_HABILITATION],[ACM_WEB_ROUTE],
[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION] 
from ACM_HABILITATION where GROUPE_ID = 1

