-- ACM_LOAN_PARTICIPANTS
CREATE INDEX id_acm_loan_participant ON ACM_LOAN_PARTICIPANTS (ID_ACM_LOAN);
CREATE INDEX username_loan_participant ON ACM_LOAN_PARTICIPANTS (username);

-- ACM_LOAN
CREATE INDEX index_ID_ACM_LOAN ON ACM_LOAN (ID_ACM_LOAN);
CREATE INDEX index_ACM_LOAN_STATUT ON ACM_LOAN (STATUT); 
CREATE INDEX index_ACM_LOAN_OWNER ON ACM_LOAN (LOAN_OWNER);
CREATE INDEX index_ACM_LOAN_ACCOUNT_NUMBER_EXTERN ON ACM_LOAN (ACCOUNT_NUMBER_EXTERN);
CREATE INDEX index_ACM_LOAN_BranchID ON ACM_LOAN (BranchID);
CREATE INDEX index_ACM_LOAN_ENABLED ON ACM_LOAN (ACM_ENABLED);

-- ACM_CUSTOMER
CREATE INDEX index_ID_ACM_CUSTOMER  ON ACM_CUSTOMER (ID_ACM_CUSTOMER);
CREATE INDEX index_ACM_CUSTOMER_BRANCH_ID  ON ACM_CUSTOMER (BRANCH_ID);
CREATE INDEX index_ACM_CUSTOMER_NUMBER ON ACM_CUSTOMER (CUSTOMER_NUMBER);
CREATE INDEX index_ACM_CUSTOMER_ENABLED  ON ACM_CUSTOMER (ACM_ENABLED);

-- ACM_LOAN_APPROVAL_HISTORIQUE
CREATE INDEX index_ACM_LOAN_APPROVAL_HISTORIQUE_ID_LOAN  ON ACM_LOAN_APPROVAL_HISTORIQUE (ID_ACM_LOAN);
CREATE INDEX index_ACM_LOAN_APPROVAL_HISTORIQUE_ENABLED  ON ACM_LOAN_APPROVAL_HISTORIQUE (ACM_ENABLED);

-- ACM_CUSTOMER_DESICION
CREATE INDEX index_ACM_CUSTOMER_DESICION_ID_LOAN  ON ACM_CUSTOMER_DESICION (ID_ACM_LOAN);
CREATE INDEX index_ACM_CUSTOMER_DESICION_ENABLED  ON ACM_CUSTOMER_DESICION (ACM_ENABLED);

-- ACM_ENVIRONNEMENT
CREATE INDEX index_ACM_ENVIRONNEMENT_KEY  ON ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY);
CREATE INDEX index_ACM_ENVIRONNEMENT_ENABLED  ON ACM_ENVIRONNEMENT (ACM_ENABLED);

-- ACM_UDF_LINK
CREATE INDEX index_ACM_UDF_LINK_ID_LOAN  ON ACM_UDF_LINK (ID_LOAN);
CREATE INDEX index_ACM_UDF_LINK_ID_CUSTOMER  ON ACM_UDF_LINK (ID_CUSTOMER);
CREATE INDEX index_ACM_UDF_LINK_ENABLED  ON ACM_UDF_LINK (ACM_ENABLED);

-- ACM_USERS
CREATE INDEX index_ACM_USERS_USERNAME  ON ACM_USERS (USERNAME);
CREATE INDEX index_ACM_USERS_RESPONSABLE_ID  ON ACM_USERS (RESPONSABLE_ID);
CREATE INDEX index_ACM_USERS_ENABLED  ON ACM_USERS (ACM_ENABLED);

-- ACM_LINKS_RELATIONSHIPS
CREATE INDEX index_ACM_LINKS_RELATIONSHIPS_ID_CUSTOMER  ON ACM_LINKS_RELATIONSHIPS (ID_ACM_CUSTOMER);
CREATE INDEX index_ACM_LINKS_RELATIONSHIPS_ID_CUSTOMER_MEMBER  ON ACM_LINKS_RELATIONSHIPS (ID_ACM_CUSTOMER_MEMBER);
CREATE INDEX index_ACM_LINKS_RELATIONSHIPS_ID_LOAN  ON ACM_LINKS_RELATIONSHIPS (ID_ACM_LOAN);
CREATE INDEX index_ACM_LINKS_RELATIONSHIPS_CATEGORY  ON ACM_LINKS_RELATIONSHIPS (CATEGORY);
CREATE INDEX index_ACM_LINKS_RELATIONSHIPS_ENABLED  ON ACM_LINKS_RELATIONSHIPS (ACM_ENABLED);
