
--- ACM_HABILITATION_IHM_BUTTON
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','REFRESH_LOAN_STATUS','IHM IHM_LOAN_APPROVAL','REFRESH_LOAN_STATUS',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0 from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LOAN_APPROVAL'

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LOAN_APPROVAL' ,'loan-approval' ,'REFRESH_LOAN_STATUS'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE