
-----  ADD_CUSTOMER_LOAN in ACM_HABILITATION 
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CUSTOMER_MANAGEMENT' ,'customer-management' ,'ADD_CUSTOMER_LOAN'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

-----  ADD_CUSTOMER_LOAN button in [ACM_HABILITATION_IHM_BUTTON] 

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select'ACM','ADD_CUSTOMER_LOAN','IHM_CUSTOMER_MANAGEMENT','ADD CUSTOMER THEN ADD LOAN',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CUSTOMER_MANAGEMENT';


