--- ACM_HABILITATION_IHM_BUTTON
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','SUBMIT','IHM IHM_UPLOAD_SIGNED_AGREEMENT','IHM_UPLOAD_SIGNED_AGREEMENT',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0 from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_UPLOAD_SIGNED_AGREEMENT'

 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_UPLOAD_SIGNED_AGREEMENT' ,'upload-signed-agreement' ,'SUBMIT'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE