CREATE TABLE ACM_GENERIC_WORKFLOW_OBJECT  (
	[ID_ACM_GENERIC_WORKFLOW_OBJECT] [bigint] IDENTITY(1,1) NOT NULL,
	NAME VARCHAR (256),
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);
