CREATE TABLE ACM_CREDIT_LINE (
	ID_ACM_CREDIT_LINE bigint NOT NULL IDENTITY(1,1),
	ID_ACM_THIRD_PARTY bigint NULL,
	FUND_NAME varchar(100) NULL,
	DESCRIPTION text NULL,
	BALANCE decimal(16,4) NULL,
	CONTROL_BALANCE bit NULL,
	FUND_PRIORITY bigint NULL,
	ISSUE_DATE date NULL,
	EXPIRY_DATE date NULL,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	CONSTRAINT ACM_CREDIT_LINE_PK PRIMARY KEY (ID_ACM_CREDIT_LINE)
);

CREATE TABLE ACM_TOPPED_UP_HISTORY (
	ID_ACM_TOPPED_UP_HISTORY bigint NOT NULL IDENTITY(1,1),
	AMOUNT decimal(16,4) NULL,
	ID_CREDIT_LINE bigint NOT NULL,
	ISSUE_DATE date NULL,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	CONSTRAINT ACM_TOPPED_UP_HISTORY_PK PRIMARY KEY (ID_ACM_TOPPED_UP_HISTORY),
	CONSTRAINT ACM_TOPPED_UP_HISTORY_FK FOREIGN KEY (ID_CREDIT_LINE) REFERENCES ACM_CREDIT_LINE(ID_ACM_CREDIT_LINE)
);

CREATE TABLE ACM_CREDIT_LINE_PRODUCTS (
	ID_CREDIT_LINE bigint NOT NULL,
	ID_PRODUCT bigint NOT NULL,
	CONSTRAINT ACM_CREDIT_LINE_PRODUCTS_FK FOREIGN KEY (ID_PRODUCT) REFERENCES ACM_PRODUCT(ID_ACM_PRODUCT),
	CONSTRAINT ACM_CREDIT_LINE_PRODUCTS_FK_1 FOREIGN KEY (ID_CREDIT_LINE) REFERENCES ACM_CREDIT_LINE(ID_ACM_CREDIT_LINE)
);


---Add credit line screen
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_ADD_CREDIT_LINE','add-credit-line' ,'page Add credit line' ,1,GETDATE(),'ADMIN',0);
---List credit line screen		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_LIST_CREDIT_LINE','list-credit-line' ,'page List credit line' ,1,GETDATE(),'ADMIN',0);
	
--- ACM_HABILITATION_IHM_BUTTON Update credit line

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','UPDATE','IHM_LIST_CREDIT_LINE','UPDATE CREDIT LINE',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LIST_CREDIT_LINE';

--- ACM_HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_ADD_CREDIT_LINE' ,'add-credit-line' ,'IHM'  ,1,GETDATE(),'ADMIN',0, 'ADD CREDIT LINE SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_CREDIT_LINE' ,'list-credit-line' ,'IHM'  ,1,GETDATE(),'ADMIN',0, 'CREDIT LINE LIST SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_CREDIT_LINE' ,'list-credit-line' ,'UPDATE'  ,1,GETDATE(),'ADMIN',0, 'UPDATE CREDIT LINE' from ACM_GROUPE
select * from ACM_HABILITATION where ACM_HABILITATION='IHM_ADD_CREDIT_LINE' ;

Update ACM_HABILITATION Set ID_ACM_HABILITATION_IHM_ROUTE=(select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE='IHM_ADD_CREDIT_LINE') 
where ACM_HABILITATION='IHM_ADD_CREDIT_LINE' ;

Update ACM_HABILITATION Set ID_ACM_HABILITATION_IHM_ROUTE=(select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE='IHM_LIST_CREDIT_LINE') 
where ACM_HABILITATION='IHM_LIST_CREDIT_LINE' ;

/*INSERT INTO ACM_MODULE
(MODULE)
VALUES(N'CREDIT_LINE');*/

Update ACM_HABILITATION_IHM_ROUTE SET RACINE_ID= (select ID_ACM_MODULE from ACM_MODULE WHERE MODULE='ACMCORE') 
WHERE CODE_IHM_ROUTE IN ('IHM_ADD_CREDIT_LINE', 'IHM_LIST_CREDIT_LINE');
