CREATE TABLE ACM_GENERIC_WORKFLOW_OBJECT(
	[ID_ACM_GENERIC_WORKFLOW_OBJECT] [bigint] IDENTITY(1,1) NOT NULL primary key,
	NAME VARCHAR (256),
	

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);

CREATE TABLE [dbo].[ACM_PLANNING_CRON](
	[ID_ACM_PLANNING_CRON ] [bigint] IDENTITY(1,1) NOT NULL primary key,
	[DAY_REP] [int] NULL,
	[CATEGORY] [varchar](50) NULL,
	[LST_DAY] [varchar](100) NULL,
	[DATE_OF_REP] [date] NULL,
	[BEGIN_OR_END_MONTH] [varchar](5) NULL,
	[DATE_OF_MONTH] [int] NULL,
	[SELECTED_DAY] [varchar](50) NULL,
	[NBR_MONTH] [varchar](50) NULL,
	[MONTH] [varchar](50) NULL,

); 


 

CREATE TABLE ACM_ITEM  (
	ID_ACM_ITEM [bigint] IDENTITY(1,1) NOT NULL primary key,
	ID_ACM_GENERIC_WORKFLOW_OBJECT [bigint] NULL, 
	ACCESS_BRANCHE  VARCHAR (256) NULL , 
	ID_ACM_INSTANCE_ITEM_ACTUAL_STEP [bigint] NULL, 
	STATUS  INTEGER NULL , 
	ID_ACTUAL_STEP_WF [bigint] NULL,
	OWNER VARCHAR (256) NULL , 
	OWNER_NAME VARCHAR (256) NULL , 
	OWNER_EMAIL  VARCHAR (256) NULL ,
	PORTFOLIO_ID [bigint] NULL , 
	GROUP_OWNER_NAME VARCHAR (256) NULL ,
	GROUP_OWNER  VARCHAR (256) NULL ,
	review_from_step  [bigint] null , 



	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
);







CREATE TABLE [dbo].[ACM_ITEM_INSTANCE](
	[ID_ACM_ITEM_INSTANCE] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ACM_ITEM] [bigint] NOT NULL,
	[ID_ACM_WORKFLOW_STEP] [bigint] NOT NULL,
	[LIBELLE] [varchar](512) NULL,
	[DESCRIPTION] [varchar](512) NULL,
	[STATUT_ITEM] [bigint]  NULL,
	[CODE_STATUT_ITEM]  [varchar](512) NULL ,
	[IHM_WEB_ROOT] [varchar](512) NULL , 
	[ORDER_ETAPE_PROCESS] [bigint]  , 
	[review_from_step]  [bigint] null,
	[ACTION_USER]  [varchar](256) NULL,
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [datetime] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [datetime] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL

) 

ALTER TABLE [dbo].[ACM_ITEM_INSTANCE]  WITH CHECK ADD FOREIGN KEY([ID_ACM_ITEM])
REFERENCES [dbo].[ACM_ITEM] ([ID_ACM_ITEM])  ; 

ALTER TABLE [ACM_ITEM_INSTANCE]
ADD CONSTRAINT pk_constraint  PRIMARY KEY ([ID_ACM_ITEM_INSTANCE]);

CREATE TABLE ACM_ITEM_NOTE(
	ID_NOTE_ITEM BIGINT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ACTION VARCHAR(150) NOT NULL,
	COMMENT VARCHAR(512) NOT NULL ,
    ITEM_ID BIGINT ,


	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
alter table ACM_CALENDAR_EVENT add ID_ACM_ITEM bigint ; 
alter table ACM_CONDITIONNAL_APPROVE add ID_ACM_ITEM bigint ; 
CREATE TABLE [dbo].[ACM_RISQUE_TYPE_ECHELLE](
	[ID_ACM_SETTING_TYPE_ECHELLE] [bigint] IDENTITY(1,1) NOT NULL,
	[LABEL] [varchar](256) NULL,
	[DESCRIPTION] [varchar](256) NULL,
	[ID_ACM_SETTING_TYPE_RISQUE] [bigint] NULL
) 

CREATE TABLE [dbo].[ACM_STEP_RISQUE_SETTING](
	[ID_ACM_STEP_RISQUE_SETTING] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ACM_WORKFLOW_STEP][bigint] NULL,
	[ID_ACM_SETTING_TYPE_RISQUE][bigint] NULL,
	[EDITABLE] bit null
) 

CREATE TABLE ACM_WORKFLOW_STEP_ACM_DOCUMENT_TYPE (
 ACM_WORKFLOW_STEP_ID BIGINT NOT NULL,
 ID_ACM_SETTING_DOC_TYPE BIGINT NOT NULL

 PRIMARY KEY (ACM_WORKFLOW_STEP_ID,ID_ACM_SETTING_DOC_TYPE)

 FOREIGN KEY (ACM_WORKFLOW_STEP_ID) REFERENCES ACM_WORKFLOW_STEP(ID_ACM_WORKFLOW_STEP),
 FOREIGN KEY (ID_ACM_SETTING_DOC_TYPE) REFERENCES ACM_SETTING_DOC_TYPE(ID_ACM_SETTING_DOC_TYPE),
);


INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]
           ([CLIENT]
           ,[CODE_IHM_ROUTE]
           ,[IHM_ROUTE]
           ,[DESCRIPTION]
           ,[RACINE_ID]
           ,[ACM_ENABLED]
           ,[DATE_INSERTION]
           ,[INSERT_BY]
           ,[DATE_LAST_UPDATE]
           ,[UPDATED_BY]
           ,[ACM_VERSION]
           ,[SETTINGS_WORKFLOW]
           ,[MODULE_ROUTE])
     VALUES
           ('ACM'
           ,'IHM_GENERIC_WF'
           ,'generic-wf-screen'
           ,'screen of generic work flow'
           ,3
           ,1
           ,'2023-08-12'
           ,'ADMIN'
           ,null
           ,null
           ,0
           ,1
           ,'acm') ; 




alter table ACM_DOCUMENTS add ID_ITEM_INSTANCE bigint ; 



CREATE TABLE [dbo].[ACM_ITEM_RISQUE_SETTING](
	[ID_ITEM_INSTANCE_RISQUE_SETTING] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ACM_ITEM][bigint] NULL,
	[ID_ACM_SETTING_TYPE_RISQUE][bigint] NULL,
	[ID_SELECTED_ECHELLE][bigint] NULL,

	 
) 

CREATE TABLE [dbo].[ACM_SETTING_TYPE_RISQUE](
	[ID_ACM_SETTING_TYPE_RISQUE] [bigint] IDENTITY(1,1) NOT NULL,
	[LABEL] [varchar](256) NULL,
	[DESCRIPTION] [varchar](256) NULL,
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [datetime] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [datetime] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL
)






INSERT INTO [dbo].[ACM_SETTING_MOTIFS_REJET]
           ([CATEGORIE]
           ,[CODE]
           ,[LIBELLE]
           ,[DESCRIPTION]
           ,[ACM_ENABLED]
           ,[DATE_INSERTION]
           ,[INSERT_BY]
           ,[DATE_LAST_UPDATE]
           ,[UPDATED_BY]
           ,[ACM_VERSION]
           ,[CODE_EXTERNAL])
     VALUES
           ('GENERIC_WF'
           ,'GENERIC_WF'
           ,'GENERIC_WF'
           ,'GENERIC_WF'
           ,1
           ,'2023-12-19'
           ,'Admin Super (ACM SUPER ADMIN GROUPE)'
           ,'2023-12-19'
           ,'Agent ACM (ACM SUPER ADMIN GROUPE)'
           ,0
           ,NULL)

alter table ACM_ITEM_INSTANCE add  ACTION_USER varchar(256) NULL 

alter table ACM_WORKFLOW_STEP add  OBJECT_ID [bigint] null  ;
alter table ACM_WORKFLOW_STEP add  ID_PLANING [bigint] null  ; 





-- ADD HABILITATION IHM_CREATE_ITEM_WF
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )
VALUES('ACM','IHM_CREATE_ITEM_WF','create-item' ,'page create task' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CREATE_ITEM_WF' ,'create-item' ,'IHM',1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CREATE_ITEM_WF') from ACM_GROUPE ; 


-- ADD HABILITATION IHM_GENERIC_WF_SCREEN
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )
VALUES('ACM','IHM_GENERIC_WF_DASHBORD','generic-wf-dashbord' ,'page generic wf dashbord' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_GENERIC_WF_DASHBORD' ,'generic-wf-dashbord' ,'IHM',1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_GENERIC_WF_DASHBORD') from ACM_GROUPE ; 

-- ADD HABILITATION IHM_GENERIC_WF_SCREEN
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )
VALUES('ACM','IHM_GENERIC_WF_SCREEN','generic-wf-screen' ,'page generic wf dashbord' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_GENERIC_WF_SCREEN' ,'generic-wf-screen' ,'IHM',1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_GENERIC_WF_SCREEN') from ACM_GROUPE ; 


-- ADD HABILITATION UNASSIGNED COLLECTIONS
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[RACINE_ID] )
VALUES('ACM','IHM_GENERIC_WF_UNASSIGNED','unassigned-wf' ,'page generic wf dashbord' ,1,GETDATE(),'ADMIN',0 , (select ID_ACM_MODULE from ACM_MODULE where MODULE ='ACMCORE' ));


INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[ID_ACM_HABILITATION_IHM_ROUTE] )
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_GENERIC_WF_UNASSIGNED' ,'unassigned-wf' ,'IHM',1,GETDATE(),'ADMIN',0 , (select ID_ACM_HABILITATION_IHM_ROUTE from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_GENERIC_WF_SCREEN') from ACM_GROUPE ; 







