ALTER TABLE ACM_LOAN ADD LOAN_OWNER VARCHAR (512) NULL;

-----------------------
ALTER TABLE ACM_USERS DROP COLUMN RESPONSABLE_ID ;

-----------------------
ALTER TABLE ACM_USERS ADD RESPONSABLE_ID VARCHAR (256) NULL;  
ALTER TABLE ACM_USERS ADD NAME VARCHAR (256) NULL; 
ALTER TABLE ACM_USERS ADD SUR_NAME VARCHAR (256) NULL; 
ALTER TABLE ACM_USERS ADD EMAIL VARCHAR (512) NULL;     
 