 
 --Google maps key
 INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('GOOGLE_MAPS_KEY', 'AIzaSyBSvnIMtXg8YuzjYF1oUPwsyHx9UolxTtg', 1, GETDATE(), 0, 'TECHNICAL');