CREATE TABLE ACM_ADDRESS_HISTORIQUE(
	ID_ACM_ADDRESS_HISTORIQUE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_ADDRESS BIGINT,
	
	OLD_ADDRESS VARCHAR(MAX),
	NEW_ADDRESS VARCHAR(MAX),
	REASONUPDATE VARCHAR(500),
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL)