   -- ADD NEW COLUMN TYPE_VALUE type of value ---
   ALTER TABLE ACM_ENVIRONNEMENT ADD TYPE_VALUE VARCHAR (256) NULL


-- set category reminder ---
update ACM_ENVIRONNEMENT SET CATEGORY = 'REMINDER' where ACM_ENVIRONNEMENT_KEY in ('INITIAL_CHECK_TIME_REMINDER_ALERT','INITIAL_CHECK_TIME_REMINDER_WARNING', 'FIELD_VISIT_TIME_REMINDER_ALERT','FIELD_VISIT_TIME_REMINDER_WARNING','GUARANTOR_TIME_REMINDER_ALERT', 'GUARANTOR_TIME_REMINDER_WARNING','COLLATERAL_TIME_REMINDER_ALERT','COLLATERAL_TIME_REMINDER_WARNING', 'ADD_DOCUMENT_TIME_REMINDER_ALERT','ADD_DOCUMENT_TIME_REMINDER_WARNING','FINANCIAL_ANALYSIS_TIME_REMINDER_ALERT', 'FINANCIAL_ANALYSIS_TIME_REMINDER_WARNING','APPROVAL_L1_TIME_REMINDER_ALERT',
'APPROVAL_L1_TIME_REMINDER_WARNING','APPROVAL_L2_TIME_REMINDER_ALERT','APPROVAL_L2_TIME_REMINDER_WARNING','APPROVAL_L3_TIME_REMINDER_ALERT','APPROVAL_L3_TIME_REMINDER_WARNING',
'APPROVAL_L4_TIME_REMINDER_ALERT','APPROVAL_L4_TIME_REMINDER_WARNING','CUSTOMER_DECISION_TIME_REMINDER_ALERT','CUSTOMER_DECISION_TIME_REMINDER_WARNING','UPLOAD_SIGNED_AGREEMENT_TIME_REMINDER_ALERT',
'UPLOAD_SIGNED_AGREEMENT_TIME_REMINDER_WARNING','UPDATE_LOAN_DATA_TIME_REMINDER_ALERT','UPDATE_LOAN_DATA_TIME_REMINDER_WARNING','DISBURSEMENT_CASE_CLOSURE_TIME_REMINDER_ALERT',
'DISBURSEMENT_CASE_CLOSURE_TIME_REMINDER_WARNING','REVIEW_TIME_REMINDER_ALERT','REVIEW_TIME_REMINDER_WARNING','SCREENING_TIME_REMINDER_ALERT','SCREENING_TIME_REMINDER_WARNING',
'AUDIT_TIME_REMINDER_ALERT','AUDIT_TIME_REMINDER_WARNING','RISK_TIME_REMINDER_ALERT','RISK_TIME_REMINDER_WARNING')
 -- set category functionnal ----
update ACM_ENVIRONNEMENT SET CATEGORY = 'FUNCTIONAL' where ACM_ENVIRONNEMENT_KEY  in( 'CUSTOMER_GUARANTOR', 'ASSIGN_CUSTOMER', 'ADMIN_FEE', 'APPLICATION_FEE', 'INTERNET_BANKING', 'COMMUNICATION_MB_IB')

--- set type of value as INPUT ----
update ACM_ENVIRONNEMENT SET TYPE_VALUE = 'INPUT' where ACM_ENVIRONNEMENT_KEY in ('INITIAL_CHECK_TIME_REMINDER_ALERT','INITIAL_CHECK_TIME_REMINDER_WARNING', 'FIELD_VISIT_TIME_REMINDER_ALERT','FIELD_VISIT_TIME_REMINDER_WARNING','GUARANTOR_TIME_REMINDER_ALERT', 'GUARANTOR_TIME_REMINDER_WARNING','COLLATERAL_TIME_REMINDER_ALERT','COLLATERAL_TIME_REMINDER_WARNING', 'ADD_DOCUMENT_TIME_REMINDER_ALERT','ADD_DOCUMENT_TIME_REMINDER_WARNING','FINANCIAL_ANALYSIS_TIME_REMINDER_ALERT', 'FINANCIAL_ANALYSIS_TIME_REMINDER_WARNING','APPROVAL_L1_TIME_REMINDER_ALERT',
'APPROVAL_L1_TIME_REMINDER_WARNING','APPROVAL_L2_TIME_REMINDER_ALERT','APPROVAL_L2_TIME_REMINDER_WARNING','APPROVAL_L3_TIME_REMINDER_ALERT','APPROVAL_L3_TIME_REMINDER_WARNING',
'APPROVAL_L4_TIME_REMINDER_ALERT','APPROVAL_L4_TIME_REMINDER_WARNING','CUSTOMER_DECISION_TIME_REMINDER_ALERT','CUSTOMER_DECISION_TIME_REMINDER_WARNING','UPLOAD_SIGNED_AGREEMENT_TIME_REMINDER_ALERT',
'UPLOAD_SIGNED_AGREEMENT_TIME_REMINDER_WARNING','UPDATE_LOAN_DATA_TIME_REMINDER_ALERT','UPDATE_LOAN_DATA_TIME_REMINDER_WARNING','DISBURSEMENT_CASE_CLOSURE_TIME_REMINDER_ALERT',
'DISBURSEMENT_CASE_CLOSURE_TIME_REMINDER_WARNING','REVIEW_TIME_REMINDER_ALERT','REVIEW_TIME_REMINDER_WARNING','SCREENING_TIME_REMINDER_ALERT','SCREENING_TIME_REMINDER_WARNING',
'AUDIT_TIME_REMINDER_ALERT','AUDIT_TIME_REMINDER_WARNING','RISK_TIME_REMINDER_ALERT','RISK_TIME_REMINDER_WARNING')

-- set type of value as CHECKBOX ---
update ACM_ENVIRONNEMENT SET TYPE_VALUE = 'CHECKBOX' where ACM_ENVIRONNEMENT_KEY  in( 'CUSTOMER_GUARANTOR', 'ASSIGN_CUSTOMER', 'ADMIN_FEE', 'APPLICATION_FEE', 'INTERNET_BANKING', 'COMMUNICATION_MB_IB')








