-- module internet banking setting --
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('INTERNET_BANKING', '1', 1, '2021-06-09', 0, 'FUNCTIONAL');