-- LOAN : 0 
-- CLIENT : 1
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('ID_CARD','ID Card','Identity Card',1,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('PASS','Passport','Passport',1,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('PHOTO','Photo','Photo Identity Proof',1,1,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('INC_STAT','Income Statement','Income Statement',0,0,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('BANK_S','Bank Statement','Bank Statement',0,0,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('DRIV_LIC','Driving license','Driving license',1,0,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('BILL','Bill','Residence Address Proof',0,0,GETDATE(),1,GETDATE(),'ADMIN',0);

INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('OTHER_LOAN','Other Loan','Loan - Other documents',0,0,GETDATE(),1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_TYPE]([CODE],[LIBELLE],[DESCRIPTION],[CATEGORIE],[UNIQUENESS],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
VALUES  ('OTHER_CLI','Other Client','Client - Other documents',1,0,GETDATE(),1,GETDATE(),'ADMIN',0);

