-- ACM : DATA BASE

--- RESET DB : 
IF OBJECT_ID('dbo.ACM_DOCUMENTS', 'U') IS NOT NULL
DROP TABLE dbo.ACM_DOCUMENTS;
-------------

----- TABLE : ACM_DOCUMENTS
 
CREATE TABLE ACM_DOCUMENTS(
    ID_ACM_DOCUMENTS BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ACM_LOAN BIGINT,
	ID_CUSTOMER BIGINT,
	ID_ACM_SETTING_DOC_TYPE BIGINT,
	ID_DOCUMENT_GED VARCHAR (256) NULL,
    TITRE  VARCHAR (512) NOT NULL,
    DESCRIPTION  VARCHAR (1000) NULL,
    AUTEUR VARCHAR (256) NULL,
    DATE_CREATION DATETIME NULL,
		
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL,
	
	FOREIGN KEY (ID_ACM_LOAN) REFERENCES ACM_LOAN (ID_ACM_LOAN),
	FOREIGN KEY (ID_ACM_SETTING_DOC_TYPE) REFERENCES ACM_SETTING_DOC_TYPE (ID_ACM_SETTING_DOC_TYPE) 
);