
     INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (1,'SOUYOULA',N'سيولة',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (2,'MACHROU3',N'مشروع',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (3,'TADHAMOUN',N'تضامن',1,GETDATE(),'ADMIN',0);
	 
	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (4,'SABA',N'صابة',1,GETDATE(),'ADMIN',0);
	
	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (5,'PH',N'قرض شرفي',1,GETDATE(),'ADMIN',0);
	 
	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (6,'HLIBNA',N'حليبنا',1,GETDATE(),'ADMIN',0);
	 
	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (7,'Asalna',N'عسلنا',1,GETDATE(),'ADMIN',0);
	 
	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (20,'ENTILEK',N'إنطلاق',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (21,'TANMYA',N'تنمية',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (22,'TAWFIK',N'توفيق',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (23,'9rayti',N'قرايتي',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (24,'Dari',N'داري',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (25,'Dari+',N'+داري',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (26,'A3yedna',N'أعيادنا',1,GETDATE(),'ADMIN',0);

	 INSERT INTO [dbo].[ACM_PRODUCT] (ID_ACM_PRODUCT,[CODE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES (27,'EMTIYEZ',N'إمتياز',1,GETDATE(),'ADMIN',0);
