
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(1 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(3 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(6 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(20 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(21 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(22 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(23 , 1 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 2 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 3 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 4 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 5 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 6 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 7 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 8 , 1,GETDATE() ,1,GETDATE(),'ADMIN',0);
INSERT INTO [dbo].[ACM_SETTING_DOC_PRODUCT] ([PRODUCT_ID] ,[ID_ACM_SETTING_DOC_TYPE],[MANDATORY],[DATE_DEBUT],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
     VALUES(26 , 9 , 0,GETDATE() ,1,GETDATE(),'ADMIN',0);
 


