CREATE TABLE ACM_MODULE(
    ID_ACM_MODULE BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MODULE VARCHAR (256),
 	
);
Alter table ACM_habilitation
add ID_ACM_MODULE bigint

ALTER TABLE ACM_HABILITATION
ADD CONSTRAINT FK_ACM_HABILITATION_MODULE
FOREIGN KEY (ID_ACM_MODULE) REFERENCES ACM_MODULE(ID_ACM_MODULE);

 INSERT INTO ACM_ENVIRONNEMENT (ACM_ENVIRONNEMENT_KEY,ACM_ENVIRONNEMENT_VALUE,ACM_ENABLED,DATE_INSERTION,INSERT_BY,DATE_LAST_UPDATE,UPDATED_BY,ACM_VERSION,DESCRIPTION,CATEGORY,TYPE_VALUE) VALUES
	 ('KEY_LICENCE','v8qcTQzVR+YJRmrbqQnLEJNIkOWOPd6Ken1QietKys6GR4iRT092tRiqMJG/qrQswajol76kTBlAbRlzznRWSMUaG25nsXSh9gMQ2kIkaROLMt/AHFaB7YMhce7Y/D6n2kcKz4BMbYoYuCJ/ORMMnkuDomMGobtMlTRTq69GRkD0UhhnbgMHUcqSnIsr3QZ/VJ5OWKOdk/KMEmaCGnIhT6r07WwSmNVbYq3I9UMtppCGoMxCHFgGIKHBD7KFZyECtfX56tSl6lDgQD8TUKYhjUzITDv0IVWWcHIQt5B294K9FdNLdb/SKuz6HnJKVZO8GviGHPqYaOomw9/G/Ni1Eg==',1,'2022-07-18',NULL,'2022-07-18',N'Admin Super (ACM SUPER ADMIN GROUPE)',4,'crypted key',N'TECHNICAL',NULL)

alter table ACM_ENVIRONNEMENT 
ALTER COLUMN ACM_ENVIRONNEMENT_VALUE varchar(2000);


ALTER TABLE dbo.ACM_HABILITATION 
ADD ID_ACM_HABILITATION_IHM_ROUTE  bigint NULL ;

UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE;


insert into ACM_MODULE (MODULE) values ('JE') 
insert into ACM_MODULE (MODULE) values ('COLLECTIONS') ; 
insert into ACM_MODULE (MODULE) values ('ACMCORE') ; 
insert into ACM_MODULE (MODULE) values ('LEGAL') ; 
insert into ACM_MODULE (MODULE) values ('SUPPLIER') ; 

UPDATE ACM_HABILITATION_IHM_ROUTE 
SET racine_id = 3 where CODE_IHM_ROUTE not like '%COLLECTION%' and CODE_IHM_ROUTE not Like '%LEGAL%'
and  CODE_IHM_ROUTE not like '%SUPPLIER%' ; 

UPDATE ACM_HABILITATION_IHM_ROUTE 
SET racine_id = 2 where CODE_IHM_ROUTE like '%COLLECTION%' ; 

UPDATE ACM_HABILITATION_IHM_ROUTE 
SET racine_id = 5 where CODE_IHM_ROUTE like '%SUPPLIER%' ; 

UPDATE ACM_HABILITATION_IHM_ROUTE 
SET racine_id = 5 where CODE_IHM_ROUTE like '%ASSET%' ; 

UPDATE ACM_HABILITATION_IHM_ROUTE 
SET racine_id = 4 where CODE_IHM_ROUTE like '%LEGAL%' ; 


