
---Add supplier screen
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_ADD_SUPPLIER','supplier-add' ,'page Add Supplier' ,1,GETDATE(),'ADMIN',0);
---List supplier screen		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_LIST_SUPPLIER','supplier-list' ,'page List Supplier' ,1,GETDATE(),'ADMIN',0);
	
--- ACM_HABILITATION_IHM_BUTTON
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','SAVE','IHM_ADD_SUPPLIER','ADD SUPPLIER',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_ADD_SUPPLIER';

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','SUPPLIER_360','IHM_LIST_SUPPLIER','SUPPLIER 360',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LIST_SUPPLIER';

INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','UPDATE','IHM_LIST_SUPPLIER','UPDATE SUPPLIER',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LIST_SUPPLIER';

--- ACM_HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_ADD_SUPPLIER' ,'supplier-add' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'ADD SUPPLIER SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_SUPPLIER' ,'supplier-list' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'SUPPLIER LIST SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_SUPPLIER' ,'supplier-list' ,'SUPPLIER_360'  ,0,GETDATE(),'ADMIN',0, 'SUPPLIER 360' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_SUPPLIER' ,'supplier-list' ,'UPDATE'  ,0,GETDATE(),'ADMIN',0, 'UPDATE SUPPLIER' from ACM_GROUPE


---Add ASSETS screen
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_ADD_ASSET','add-asset' ,'page Add ASSET' ,1,GETDATE(),'ADMIN',0);
---List ASSETS screen		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_LIST_ASSET','list-asset' ,'page List Asset' ,1,GETDATE(),'ADMIN',0);

--- ACM_HABILITATION_IHM_BUTTON
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','SAVE','IHM_ADD_ASSET','ADD ASSET',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_ADD_ASSET';
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','UPDATE','IHM_UPDATE_ASSET','UPDATE ASSET',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LIST_ASSET';
	
		
--- ACM_HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_ADD_ASSET' ,'add-asset' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'ADD ASSET SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_ASSET' ,'list-asset' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'ASSET LIST SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_ASSET' ,'list-asset' ,'UPDATE'  ,0,GETDATE(),'ADMIN',0, 'UPDATE ASSET' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_ASSET' ,'list-asset' ,'ASSET_360'  ,0,GETDATE(),'ADMIN',0, 'ASSET 360' from ACM_GROUPE

---Add PROSPECT screen
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_ADD_PROSPECT','prospect-management' ,'page Add PROSPECT' ,1,GETDATE(),'ADMIN',0);
---List PROSPECT screen		
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
		VALUES('ACM','IHM_LIST_PROSPECT','list-prospect' ,'page List PROSPECT' ,1,GETDATE(),'ADMIN',0);

--- ACM_HABILITATION_IHM_BUTTON
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','SAVE','IHM_ADD_PROSPECT','ADD PROSPECT',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_ADD_PROSPECT';
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','UPDATE','IHM_LIST_PROSPECT','UPDATE PROSPECT',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0  from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_LIST_PROSPECT';
	
		
--- ACM_HABILITATION

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_ADD_PROSPECT' ,'prospect-management' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'ADD PROSPECT SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_PROSPECT' ,'list-prospect' ,'IHM'  ,0,GETDATE(),'ADMIN',0, 'PROSPECT LIST SCREEN' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_LIST_PROSPECT' ,'list-prospect' ,'UPDATE'  ,0,GETDATE(),'ADMIN',0, 'UPDATE PROSPECT' from ACM_GROUPE

UPDATE ACM_HABILITATION
SET ID_ACM_HABILITATION_IHM_ROUTE = IHM_ROUTE.ID_ACM_HABILITATION_IHM_ROUTE
FROM ACM_HABILITATION
INNER JOIN ACM_HABILITATION_IHM_ROUTE AS IHM_ROUTE
ON ACM_HABILITATION.ACM_HABILITATION = IHM_ROUTE.CODE_IHM_ROUTE;
