-- add TEMPORARY_RESPONSABLE, OLD_RESPONSABLE_NAME, OLD_RESPONSABLE_ID in ACM_USERS Table
ALTER TABLE ACM_USERS
ADD
TEMPORARY_RESPONSABLE BIT NULL,
OLD_RESPONSABLE_NAME  VARCHAR (256) NULL,
OLD_RESPONSABLE_ID  VARCHAR (256) NULL; 
-- set default value 0 of TEMPORARY_RESPONSABLE
update ACM_USERS set TEMPORARY_RESPONSABLE = 0
