-- add customer aml check route in [ACM_HABILITATION_IHM_ROUTE]
 INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])		    
	VALUES('ACM','IHM_CUSTOMER_AML_CHECK','customer-aml-check' ,'page customer aml check' ,1,GETDATE(),'ADMIN',0);

-- add habilitaion for customer aml check
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_CUSTOMER_AML_CHECK' ,'customer-aml-check' ,'IHM'  ,1,GETDATE(),'ADMIN',0 from ACM_GROUPE

-- add button habilitaion CHECK AML
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','CHECK_AML','IHM IHM_CUSTOMER_AML_CHECK','IHM_CUSTOMER_AML_CHECK',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0 from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CUSTOMER_AML_CHECK'

-- add habilitation CHECK AML
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_CUSTOMER_LIST' ,'customer-list' ,'CHECK_AML'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE

--add button habilitation AML DETAILS
INSERT INTO [dbo].[ACM_HABILITATION_IHM_BUTTON]([CLIENT],[CODE_IHM_BUTTON],[IHM_BUTTON],[DESCRIPTION],[ID_ACM_HABILITATION_IHM_ROUTE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'ACM','AML_DETAILS','IHM IHM_CUSTOMER_AML_CHECK','IHM_CUSTOMER_AML_CHECK',ID_ACM_HABILITATION_IHM_ROUTE,1,GETDATE(),'ADMIN',0 from ACM_HABILITATION_IHM_ROUTE where CODE_IHM_ROUTE = 'IHM_CUSTOMER_AML_CHECK'
 -- ADD habilitation AML_DETAILS
 INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])
select 'READ','ACM' ,id_acm_groupe ,'IHM_CUSTOMER_LIST' ,'customer-list' ,'AML_DETAILS'  ,0,GETDATE(),'ADMIN',0 from ACM_GROUPE