CREATE TABLE ACM_SETTING_JOURNAL_ENTRY_TYPE(
    ID_ACM_SETTING_JOURNAL_ENTRY BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE  VARCHAR (256) NOT NULL,
	LIBELLE  VARCHAR (512) NULL,
    DESCRIPTION  VARCHAR (512) NULL,
	 
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATE NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATE NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);



CREATE TABLE [dbo].[ACM_SETTING_JOURNAL_ENTERIES](
	[ID_ACM_SETTING_JOURNAL_ENTERIES] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](256) NOT NULL,
	[LIBELLE] [varchar](512) NULL,
	[DESCRIPTION] [varchar](512) NULL,
	[AMOUNT] [varchar](256) NULL,
	[PERCENTAGE] [int] NULL,
	[DEBIT_ACCOUNT] [varchar](512) NULL,
	[CREDIT_ACCOUNT] [varchar](512) NULL,
	[ID_ACM_SETTING_JOURNAL_ENTRY] [bigint] NULL,
	[ACM_ENABLED] [bit] NOT NULL,
	[DATE_INSERTION] [date] NULL,
	[INSERT_BY] [varchar](256) NULL,
	[DATE_LAST_UPDATE] [date] NULL,
	[UPDATED_BY] [varchar](256) NULL,
	[ACM_VERSION] [int] NULL,
	[ID_CREDIT_ACCOUNT] [bigint] NULL,
	[ID_DEBIT_ACCOUNT] [bigint] NULL
)


CREATE TABLE ACM_SETTING_JOURNAL_ENTRY_TYPE_ACM_WORKFLOW_STEP (
    ID_ACM_WORKFLOW_STEP BIGINT NOT NULL,
    ID_ACM_SETTING_JOURNAL_ENTRY BIGINT NOT NULL,
    PRIMARY KEY (ID_ACM_WORKFLOW_STEP, ID_ACM_SETTING_JOURNAL_ENTRY),
    FOREIGN KEY (ID_ACM_WORKFLOW_STEP) REFERENCES ACM_WORKFLOW_STEP (ID_ACM_WORKFLOW_STEP),
    FOREIGN KEY (ID_ACM_SETTING_JOURNAL_ENTRY) REFERENCES ACM_SETTING_JOURNAL_ENTRY_TYPE (ID_ACM_SETTING_JOURNAL_ENTRY)
);


alter table ACM_LOAN
add  TOTAL_INTEREST decimal(16, 4) ; 

alter table ACM_LOAN
add  PERSONAL_CONTRIBUTION decimal(16, 4)

