IF OBJECT_ID('dbo.ACM_IHM_FORM', 'U') IS NOT NULL
DROP TABLE dbo.ACM_IHM_FORM;
CREATE TABLE ACM_IHM_FORM (
    ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CODE_PAGE varchar(256),
    DESCRIPTION varchar(256),
	ID_ACM_HABILITATION_IHM_ROUTE BIGINT,

	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION datetime  NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE datetime  NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL

	FOREIGN KEY (ID_ACM_HABILITATION_IHM_ROUTE) REFERENCES ACM_HABILITATION_IHM_ROUTE(ID_ACM_HABILITATION_IHM_ROUTE),
);
IF OBJECT_ID('dbo.ACM_IHM_FIELD', 'U') IS NOT NULL
DROP TABLE dbo.ACM_IHM_FIELD;
CREATE TABLE ACM_IHM_FIELD (
    ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE_FIELD varchar(256),
	TYPE_FIELD varchar(256),
	DEFAULT_VALUE varchar(256),
	TITLE varchar(255),
	DESCRIPTION varchar(256),
	PLACEHOLDER varchar(256),
	MIN INT,
	MAX INT,
	STEP INT,
	SINGLE_SELECT BIT, 
	TYPE_OPTION_VALUE varchar(256),
	ORDRE tinyint,
	
    ID_ACM_ACM_IHM_FORM BIGINT,	
    SUB_CODE_FIELD varchar(100),
	FORM_CONTROL_NAME varchar(100),
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION datetime  NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE datetime  NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT, 
	
	FOREIGN KEY (ID_ACM_ACM_IHM_FORM) REFERENCES ACM_IHM_FORM(ID),
);
IF OBJECT_ID('dbo.ACM_IHM_VALIDATOR', 'U') IS NOT NULL
DROP TABLE dbo.ACM_IHM_VALIDATOR;
CREATE TABLE ACM_IHM_VALIDATOR (
    ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CODE_VALIDATOR varchar(256),
	PARAMETER varchar(256),
	TYPE_VALIDATOR varchar(100),
	
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION datetime  NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE datetime  NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
IF OBJECT_ID('dbo.ACM_IHM_VALIDATOR_FIELD', 'U') IS NOT NULL
DROP TABLE dbo.ACM_IHM_VALIDATOR_FIELD;
CREATE TABLE ACM_IHM_VALIDATOR_FIELD (
	ID_ACM_IHM_VALIDATOR BIGINT NOT NULL,
	ID_ACM_IHM_FIELD BIGINT NOT NULL
	PRIMARY KEY (ID_ACM_IHM_VALIDATOR,ID_ACM_IHM_FIELD)
	FOREIGN KEY (ID_ACM_IHM_VALIDATOR) REFERENCES ACM_IHM_VALIDATOR(ID),
	FOREIGN KEY (ID_ACM_IHM_FIELD) REFERENCES ACM_IHM_FIELD(ID),
); 
IF OBJECT_ID('dbo.ACM_IHM_FIELD_GROUPE', 'U') IS NOT NULL
DROP TABLE dbo.ACM_IHM_FIELD_GROUPE;
CREATE TABLE ACM_IHM_FIELD_GROUPE (
    ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_GROUPE BIGINT NOT NULL,
	ID_ACM_IHM_FIELD BIGINT NOT NULL,
    HABILITATION VARCHAR (256),
	
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION datetime  NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE datetime  NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL

	FOREIGN KEY (ID_GROUPE) REFERENCES ACM_GROUPE(ID_ACM_GROUPE),
	FOREIGN KEY (ID_ACM_IHM_FIELD) REFERENCES ACM_IHM_FIELD(ID),
); 

 