-- text to display from setting in the profile IB/MB
INSERT INTO [ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION],CATEGORY) 
VALUES ('COMMUNICATION_MB_IB', 'ANNOUNCEMENT', 1, '2021-04-26', 0, 'FUNCTIONAL');