--ADD ROUTE HABILITATION collections details
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])	        
VALUES('ACM','IHM_COLLECTION_DETAILS','/loan-collection-details' ,'page COLLECTION DETAILS' ,1,GETDATE(),'ADMIN',0);
		

--ADD ROUTE HABILITATION collections
INSERT INTO [dbo].[ACM_HABILITATION_IHM_ROUTE]([CLIENT],[CODE_IHM_ROUTE],[IHM_ROUTE],[DESCRIPTION],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION])            
VALUES('ACM','IHM_COLLECTIONS','collections' ,'page collections' ,1,GETDATE(),'ADMIN',0);
    
    --- ADD HABILITATION 
INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_COLLECTIONS' ,'collections' ,'IHM'  ,1,GETDATE(),'ADMIN',0,'COLLECTIONS' from ACM_GROUPE

INSERT INTO [dbo].[ACM_HABILITATION]([ACTIONS],[CLIENT],[GROUPE_ID],[ACM_HABILITATION],[ACM_WEB_ROUTE],[VALUE],[ACM_ENABLED],[DATE_INSERTION],[INSERT_BY],[ACM_VERSION],[DESCRIPTION])
select 'READ','ACM' ,ID_ACM_GROUPE ,'IHM_COLLECTIONS_DETAILS' ,'loan-collection-details' ,'IHM'  ,1,GETDATE(),'ADMIN',0,'COLLECTIONS' from ACM_GROUPE