IF OBJECT_ID('dbo.ACM_REPORT_SEARCH_HISTORY', 'U') IS NOT NULL
DROP TABLE dbo.ACM_REPORT_SEARCH_HISTORY;

CREATE TABLE ACM_REPORT_SEARCH_HISTORY(
    ID_ACM_REPORT_SEARCH_HISTORY BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    SEARCH_DATA_JSON VARCHAR(MAX) NOT NULL,
	USERNAME VARCHAR (256) NOT NULL,
	LABEL_SEARCH_HISTORY VARCHAR (512) NOT NULL,
	REPORT_NAME VARCHAR (512) NOT NULL,
	
	ACM_ENABLED BIT NOT NULL,
	DATE_INSERTION DATETIME NULL,
	INSERT_BY  VARCHAR (256) NULL,
	DATE_LAST_UPDATE DATETIME NULL,
	UPDATED_BY  VARCHAR (256) NULL,
	ACM_VERSION INT NULL
);
