  INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION], [CATEGORY]) 
VALUES ('MEMBERS_NUMBER_MAX', '5', 1, '2021-04-16', 0, 'FUNCTIONAL');

  INSERT INTO [DBO].[ACM_ENVIRONNEMENT]([ACM_ENVIRONNEMENT_KEY], [ACM_ENVIRONNEMENT_VALUE], [ACM_ENABLED], [DATE_INSERTION], [ACM_VERSION], [CATEGORY]) 
VALUES ('MEMBERS_NUMBER_MIN', '2', 1, '2021-04-16', 0, 'FUNCTIONAL');
